// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.12.4
// source: fleet.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FleetControl_CommandStream_FullMethodName = "/fleet.FleetControl/CommandStream"
	FleetControl_RegisterAgent_FullMethodName = "/fleet.FleetControl/RegisterAgent"
	FleetControl_ReportResult_FullMethodName  = "/fleet.FleetControl/ReportResult"
	FleetControl_ExecuteTask_FullMethodName   = "/fleet.FleetControl/ExecuteTask"
	FleetControl_CancelTask_FullMethodName    = "/fleet.FleetControl/CancelTask"
	FleetControl_GetFleetState_FullMethodName = "/fleet.FleetControl/GetFleetState"
)

// FleetControlClient is the client API for FleetControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// FleetControl - Central command and control service
type FleetControlClient interface {
	// Bidirectional streaming for real-time command/result exchange
	CommandStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, ServerMessage], error)
	// Agent registration on connection
	RegisterAgent(ctx context.Context, in *RegisterAgentRequest, opts ...grpc.CallOption) (*RegisterAgentResponse, error)
	// Direct result reporting (fallback for non-streaming)
	ReportResult(ctx context.Context, in *ActionResult, opts ...grpc.CallOption) (*Ack, error)
	// Request task execution
	ExecuteTask(ctx context.Context, in *ExecuteTaskRequest, opts ...grpc.CallOption) (*ExecuteTaskResponse, error)
	// Cancel running task
	CancelTask(ctx context.Context, in *CancelTaskRequest, opts ...grpc.CallOption) (*CancelTaskResponse, error)
	// Get fleet state snapshot
	GetFleetState(ctx context.Context, in *FleetStateRequest, opts ...grpc.CallOption) (*FleetStateResponse, error)
}

type fleetControlClient struct {
	cc grpc.ClientConnInterface
}

func NewFleetControlClient(cc grpc.ClientConnInterface) FleetControlClient {
	return &fleetControlClient{cc}
}

func (c *fleetControlClient) CommandStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, ServerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FleetControl_ServiceDesc.Streams[0], FleetControl_CommandStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentMessage, ServerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FleetControl_CommandStreamClient = grpc.BidiStreamingClient[AgentMessage, ServerMessage]

func (c *fleetControlClient) RegisterAgent(ctx context.Context, in *RegisterAgentRequest, opts ...grpc.CallOption) (*RegisterAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterAgentResponse)
	err := c.cc.Invoke(ctx, FleetControl_RegisterAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetControlClient) ReportResult(ctx context.Context, in *ActionResult, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, FleetControl_ReportResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetControlClient) ExecuteTask(ctx context.Context, in *ExecuteTaskRequest, opts ...grpc.CallOption) (*ExecuteTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteTaskResponse)
	err := c.cc.Invoke(ctx, FleetControl_ExecuteTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetControlClient) CancelTask(ctx context.Context, in *CancelTaskRequest, opts ...grpc.CallOption) (*CancelTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelTaskResponse)
	err := c.cc.Invoke(ctx, FleetControl_CancelTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetControlClient) GetFleetState(ctx context.Context, in *FleetStateRequest, opts ...grpc.CallOption) (*FleetStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FleetStateResponse)
	err := c.cc.Invoke(ctx, FleetControl_GetFleetState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FleetControlServer is the server API for FleetControl service.
// All implementations must embed UnimplementedFleetControlServer
// for forward compatibility.
//
// FleetControl - Central command and control service
type FleetControlServer interface {
	// Bidirectional streaming for real-time command/result exchange
	CommandStream(grpc.BidiStreamingServer[AgentMessage, ServerMessage]) error
	// Agent registration on connection
	RegisterAgent(context.Context, *RegisterAgentRequest) (*RegisterAgentResponse, error)
	// Direct result reporting (fallback for non-streaming)
	ReportResult(context.Context, *ActionResult) (*Ack, error)
	// Request task execution
	ExecuteTask(context.Context, *ExecuteTaskRequest) (*ExecuteTaskResponse, error)
	// Cancel running task
	CancelTask(context.Context, *CancelTaskRequest) (*CancelTaskResponse, error)
	// Get fleet state snapshot
	GetFleetState(context.Context, *FleetStateRequest) (*FleetStateResponse, error)
	mustEmbedUnimplementedFleetControlServer()
}

// UnimplementedFleetControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFleetControlServer struct{}

func (UnimplementedFleetControlServer) CommandStream(grpc.BidiStreamingServer[AgentMessage, ServerMessage]) error {
	return status.Error(codes.Unimplemented, "method CommandStream not implemented")
}
func (UnimplementedFleetControlServer) RegisterAgent(context.Context, *RegisterAgentRequest) (*RegisterAgentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterAgent not implemented")
}
func (UnimplementedFleetControlServer) ReportResult(context.Context, *ActionResult) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportResult not implemented")
}
func (UnimplementedFleetControlServer) ExecuteTask(context.Context, *ExecuteTaskRequest) (*ExecuteTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteTask not implemented")
}
func (UnimplementedFleetControlServer) CancelTask(context.Context, *CancelTaskRequest) (*CancelTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelTask not implemented")
}
func (UnimplementedFleetControlServer) GetFleetState(context.Context, *FleetStateRequest) (*FleetStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFleetState not implemented")
}
func (UnimplementedFleetControlServer) mustEmbedUnimplementedFleetControlServer() {}
func (UnimplementedFleetControlServer) testEmbeddedByValue()                      {}

// UnsafeFleetControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FleetControlServer will
// result in compilation errors.
type UnsafeFleetControlServer interface {
	mustEmbedUnimplementedFleetControlServer()
}

func RegisterFleetControlServer(s grpc.ServiceRegistrar, srv FleetControlServer) {
	// If the following call panics, it indicates UnimplementedFleetControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FleetControl_ServiceDesc, srv)
}

func _FleetControl_CommandStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FleetControlServer).CommandStream(&grpc.GenericServerStream[AgentMessage, ServerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FleetControl_CommandStreamServer = grpc.BidiStreamingServer[AgentMessage, ServerMessage]

func _FleetControl_RegisterAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetControlServer).RegisterAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetControl_RegisterAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetControlServer).RegisterAgent(ctx, req.(*RegisterAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetControl_ReportResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActionResult)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetControlServer).ReportResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetControl_ReportResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetControlServer).ReportResult(ctx, req.(*ActionResult))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetControl_ExecuteTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetControlServer).ExecuteTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetControl_ExecuteTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetControlServer).ExecuteTask(ctx, req.(*ExecuteTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetControl_CancelTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetControlServer).CancelTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetControl_CancelTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetControlServer).CancelTask(ctx, req.(*CancelTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetControl_GetFleetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FleetStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetControlServer).GetFleetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetControl_GetFleetState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetControlServer).GetFleetState(ctx, req.(*FleetStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FleetControl_ServiceDesc is the grpc.ServiceDesc for FleetControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FleetControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fleet.FleetControl",
	HandlerType: (*FleetControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterAgent",
			Handler:    _FleetControl_RegisterAgent_Handler,
		},
		{
			MethodName: "ReportResult",
			Handler:    _FleetControl_ReportResult_Handler,
		},
		{
			MethodName: "ExecuteTask",
			Handler:    _FleetControl_ExecuteTask_Handler,
		},
		{
			MethodName: "CancelTask",
			Handler:    _FleetControl_CancelTask_Handler,
		},
		{
			MethodName: "GetFleetState",
			Handler:    _FleetControl_GetFleetState_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CommandStream",
			Handler:       _FleetControl_CommandStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "fleet.proto",
}
