import { memo, useState, useEffect, useMemo, useCallback } from 'react'
import { Handle, Position, NodeProps, useReactFlow, useUpdateNodeInternals, useNodes } from 'reactflow'
import { ChevronDown, ChevronUp, Plus, X, Filter, Loader2, Sparkles, Download } from 'lucide-react'
import type { StartStateConfig, EndStateConfig, ActionField, DuringStateTarget, ParameterFieldSource } from '../../../types'
import { capabilityApi } from '../../../api/client'

// Local imports
import type { StateActionNodeData, NormalizedDuringStateTarget, AvailableStep } from './types'
import { OUTCOME_COLORS, OUTCOME_HANDLE_IDS, OUTCOME_OPTIONS, DURING_TARGET_OPTIONS } from './constants'
import {
  generateStatesFromNodeName,
  createAutoGeneratedGraphStates,
  schemaToFields,
  normalizeOutcomeValue,
  inferOutcomeFromEndState,
  getEndStateColor,
} from './utils'
import { GoalParametersSection } from './components'

// Re-export utilities for backward compatibility
export { generateStatesFromNodeName, createAutoGeneratedGraphStates }
export { AUTO_STATE_SUFFIXES } from './constants'

const StateActionNode = memo(({ id, data, selected }: NodeProps<StateActionNodeData>) => {
  const color = data.color || '#3b82f6'
  const { setNodes, setEdges } = useReactFlow()
  const updateNodeInternals = useUpdateNodeInternals()
  const allNodes = useNodes()
  const baseStates = data.availableStates || []
  const [expandedSection, setExpandedSection] = useState<string | null>(null)

  // Action fields from API
  const [goalFields, setGoalFields] = useState<ActionField[]>([])
  const [resultFields, setResultFields] = useState<ActionField[]>([])
  const [isLoadingFields, setIsLoadingFields] = useState(false)

  // Auto-generate states
  const autoGenerateStates = data.autoGenerateStates ?? true
  const jobName = data.jobName ?? ''

  // Compute auto-generated states
  const autoGeneratedStates = useMemo(() => {
    if (!autoGenerateStates || !jobName.trim()) return []
    return createAutoGeneratedGraphStates(jobName.trim(), id)
  }, [autoGenerateStates, jobName, id])

  // Combine base states with auto-generated ones
  const states = useMemo(() => {
    if (!autoGenerateStates || autoGeneratedStates.length === 0) return baseStates
    const autoStateCodes = autoGeneratedStates.map(s => s.code)
    return [...baseStates, ...autoStateCodes]
  }, [baseStates, autoGenerateStates, autoGeneratedStates])

  // Generate End States from result fields
  const generateEndStatesFromResults = (results: ActionField[]): EndStateConfig[] => {
    const endStates: EndStateConfig[] = []
    const now = Date.now()
    const successState = states.includes('idle') ? 'idle' : states.includes('completed') ? 'completed' : states[0] || 'idle'
    const errorState = states.includes('error') ? 'error' : states.includes('failed') ? 'failed' : states[0] || 'error'

    endStates.push({ id: `end-success-${now}`, state: successState, label: 'Success', outcome: 'success', color: OUTCOME_COLORS.success })
    endStates.push({ id: `end-failed-${now + 1}`, state: errorState, label: 'Failed', outcome: 'failed', color: OUTCOME_COLORS.failed })
    endStates.push({ id: `end-aborted-${now + 2}`, state: errorState, label: 'Aborted', outcome: 'aborted', color: OUTCOME_COLORS.aborted })

    const hasTimeout = results.some(f => f.name.includes('timeout') || f.name.includes('timed_out'))
    if (hasTimeout) {
      endStates.push({ id: `end-timeout-${now + 4}`, state: errorState, label: 'Timeout', outcome: 'timeout', color: OUTCOME_COLORS.timeout })
    }

    endStates.push({ id: `end-cancelled-${now + 5}`, state: states.includes('cancelled') ? 'cancelled' : errorState, label: 'Cancelled', outcome: 'cancelled', color: OUTCOME_COLORS.cancelled })

    return endStates
  }

  // Fetch action schema
  useEffect(() => {
    if (!data.actionType) {
      setGoalFields([])
      setResultFields([])
      return
    }

    setIsLoadingFields(true)

    capabilityApi.getByActionType(data.actionType)
      .then((capData) => {
        if (capData.agents && capData.agents.length > 0) {
          const firstAgent = capData.agents[0]
          const goalFieldsParsed = schemaToFields(firstAgent.goal_schema)
          setGoalFields(goalFieldsParsed)

          const resultFieldsParsed = schemaToFields(firstAgent.result_schema)
          setResultFields(resultFieldsParsed)

          updateData('resultFields', resultFieldsParsed.map(f => ({ name: f.name, type: f.type + (f.is_array ? '[]' : '') })))

          if (!data.endStates || data.endStates.length === 0) {
            updateData('endStates', generateEndStatesFromResults(resultFieldsParsed))
          }
        } else {
          setGoalFields([])
          setResultFields([])
          updateData('resultFields', [])
        }
      })
      .catch(() => {
        setGoalFields([])
        setResultFields([])
        updateData('resultFields', [])
      })
      .finally(() => setIsLoadingFields(false))
  }, [data.actionType])

  // Auto-expand params section when selected
  useEffect(() => {
    if (selected && !isLoadingFields && goalFields.length === 0 && data.actionType) {
      setExpandedSection('params')
    }
  }, [selected, isLoadingFields, goalFields.length, data.actionType])

  // State configurations
  const startStates = data.startStates || []
  const duringStateTargets: NormalizedDuringStateTarget[] = (data.duringStateTargets && data.duringStateTargets.length > 0)
    ? data.duringStateTargets.map(target => ({ ...target, target_type: (target.target_type || 'self') as NormalizedDuringStateTarget['target_type'] }))
    : (data.duringStates || []).filter(Boolean).slice(0, 1).map(state => ({ state, target_type: 'self' as const }))
  const endStates = data.endStates || []

  const updateData = useCallback((field: string, value: unknown) => {
    setNodes((nds) => nds.map((n) => n.id === id ? { ...n, data: { ...n.data, [field]: value } } : n))
  }, [id, setNodes])

  // Auto-apply generated states
  const applyAutoGeneratedStates = useCallback(() => {
    if (!jobName.trim()) return

    const generatedStates = generateStatesFromNodeName(jobName.trim())
    const newDuringTargets: DuringStateTarget[] = [{ state: generatedStates.during, target_type: 'self' }]

    const existingEndStates = data.endStates || []
    const existingByOutcome = new Map<string, EndStateConfig>()
    const handleIdRemap = new Map<string, string>()

    existingEndStates.forEach((endState) => {
      const inferred = normalizeOutcomeValue(endState.outcome) || inferOutcomeFromEndState(endState)
      const handleId = OUTCOME_HANDLE_IDS[inferred]
      if (handleId && endState.id !== handleId) handleIdRemap.set(endState.id, handleId)
      if (!existingByOutcome.has(inferred)) existingByOutcome.set(inferred, endState)
    })

    const buildEndState = (outcome: string, state: string, label: string, color: string): EndStateConfig => {
      const existing = existingByOutcome.get(outcome)
      return {
        ...existing,
        id: OUTCOME_HANDLE_IDS[outcome as keyof typeof OUTCOME_HANDLE_IDS],
        state,
        label: existing?.label || label,
        outcome: outcome as EndStateConfig['outcome'],
        color: existing?.color || color,
      }
    }

    const newEndStates: EndStateConfig[] = [
      buildEndState('success', generatedStates.succeed, 'Success', '#22C55E'),
      buildEndState('failed', generatedStates.failed, 'Failed', '#EF4444'),
      buildEndState('aborted', generatedStates.aborted, 'Aborted', '#EF4444'),
      buildEndState('cancelled', generatedStates.cancelled, 'Cancelled', '#6B7280'),
      buildEndState('timeout', generatedStates.timeout, 'Timeout', '#F59E0B'),
    ]

    const graphStates = createAutoGeneratedGraphStates(jobName.trim(), id)

    setNodes((nds) => nds.map((n) =>
      n.id === id ? { ...n, data: { ...n.data, duringStateTargets: newDuringTargets, endStates: newEndStates, generatedStates: graphStates } } : n
    ))

    if (handleIdRemap.size > 0) {
      setEdges((eds) => eds.map((edge) => {
        if (edge.source !== id || !edge.sourceHandle) return edge
        const mapped = handleIdRemap.get(edge.sourceHandle)
        if (!mapped || mapped === edge.sourceHandle) return edge
        return { ...edge, sourceHandle: mapped }
      }))
    }
  }, [jobName, id, data.endStates, setNodes, setEdges])

  // Toggle auto-generate states
  const toggleAutoGenerateStates = useCallback((enabled: boolean) => {
    updateData('autoGenerateStates', enabled)
    if (enabled && jobName.trim()) setTimeout(() => applyAutoGeneratedStates(), 0)
  }, [updateData, jobName, applyAutoGeneratedStates])

  // Re-apply when jobName changes
  useEffect(() => {
    if (autoGenerateStates && jobName.trim()) applyAutoGeneratedStates()
  }, [jobName, autoGenerateStates, applyAutoGeneratedStates])

  // Update ReactFlow internals after node data changes
  useEffect(() => {
    const timer = setTimeout(() => updateNodeInternals(id), 0)
    return () => clearTimeout(timer)
  }, [id, jobName, updateNodeInternals])

  const availableAgents = data.availableAgents || []
  const params = data.params || {}
  const fieldSources = data.fieldSources || {}

  // Available steps for result binding
  const availableSteps: AvailableStep[] = useMemo(() => {
    return allNodes
      .filter(node => node.type === 'action' && node.id !== id && (node.data as StateActionNodeData)?.jobName)
      .map(node => {
        const nodeData = node.data as StateActionNodeData
        return { id: node.id, name: nodeData?.jobName || node.id, resultFields: nodeData?.resultFields || [] }
      })
  }, [allNodes, id])

  // Update handlers
  const updateParam = useCallback((key: string, value: unknown) => updateData('params', { ...params, [key]: value }), [params, updateData])

  const updateFieldSource = useCallback((key: string, source: ParameterFieldSource | undefined) => {
    if (source === undefined) {
      const newFieldSources = { ...fieldSources }
      delete newFieldSources[key]
      updateData('fieldSources', Object.keys(newFieldSources).length > 0 ? newFieldSources : undefined)
    } else {
      updateData('fieldSources', { ...fieldSources, [key]: source })
    }
  }, [fieldSources, updateData])

  // Start state handlers
  const addStartState = useCallback(() => {
    const newStartState: StartStateConfig = {
      id: `start-${Date.now()}`,
      quantifier: 'self',
      state: states[0] || 'idle',
      operator: startStates.length > 0 ? 'and' : undefined,
    }
    updateData('startStates', [...startStates, newStartState])
  }, [startStates, states, updateData])

  const removeStartState = useCallback((startStateId: string) => {
    const filtered = startStates.filter(ss => ss.id !== startStateId)
    if (filtered.length > 0 && filtered[0].operator) filtered[0] = { ...filtered[0], operator: undefined }
    updateData('startStates', filtered)
  }, [startStates, updateData])

  const updateStartStateField = useCallback((startStateId: string, field: keyof StartStateConfig, value: string | undefined) => {
    updateData('startStates', startStates.map((ss, idx) => {
      if (ss.id !== startStateId) return ss
      const updated = { ...ss, [field]: value }
      if (field === 'quantifier' && value === 'self') updated.agentId = undefined
      if (field === 'quantifier' && (value === 'every' || value === 'any' || value === 'specific') && !ss.agentId && availableAgents.length > 0) {
        updated.agentId = availableAgents[0].id
      }
      if (idx === 0) updated.operator = undefined
      return updated
    }))
  }, [startStates, availableAgents, updateData])

  // End state handlers
  const addEndState = useCallback(() => {
    const newEndState: EndStateConfig = {
      id: `end-${Date.now()}`,
      state: states[0] || 'idle',
      label: `State ${endStates.length + 1}`,
      outcome: 'success',
      color: OUTCOME_COLORS.success,
    }
    updateData('endStates', [...endStates, newEndState])
  }, [endStates, states, updateData])

  const removeEndState = useCallback((endStateId: string) => {
    if (endStates.length > 1) updateData('endStates', endStates.filter(es => es.id !== endStateId))
  }, [endStates, updateData])

  const updateEndState = useCallback((endStateId: string, field: string, value: string) => {
    updateData('endStates', endStates.map(es => {
      if (es.id !== endStateId) return es
      const updated = { ...es, [field]: value }
      if (field === 'state' || field === 'label' || field === 'outcome') updated.color = getEndStateColor(updated)
      return updated
    }))
  }, [endStates, updateData])

  // During state handlers
  const addDuringState = useCallback(() => {
    if (states.length === 0) return
    updateData('duringStateTargets', [...duringStateTargets, { state: states[0], target_type: 'self' }])
  }, [states, duringStateTargets, updateData])

  const hasStartConditions = startStates.length > 0

  return (
    <div
      className={`
        relative min-w-[280px] max-w-[340px] rounded-lg overflow-visible
        bg-[#1e1e2e] border-2 shadow-lg
        ${selected ? 'border-white/60 shadow-xl shadow-blue-500/20' : 'border-primary'}
        transition-all duration-150
      `}
    >
      {/* Input Handle */}
      <Handle
        type="target"
        position={Position.Left}
        id="in"
        className="!w-4 !h-4 !bg-cyan-500 !border-2 !border-cyan-300 !rounded-full hover:!w-5 hover:!h-5 hover:!bg-cyan-400 transition-all cursor-crosshair !pointer-events-auto"
        style={{ position: 'absolute', left: -8, top: '50px', zIndex: 1000, pointerEvents: 'auto' }}
        title="입력 (이전 액션에서)"
      />

      {/* Header */}
      <div style={{ backgroundColor: `${color}25` }}>
        <div className="px-3 pt-2 pb-1 flex items-center gap-2">
          <div className="w-2 h-2 rounded-sm flex-shrink-0" style={{ backgroundColor: color }} />
          <div className="flex-1 min-w-0">
            <input
              type="text"
              value={jobName}
              onChange={(e) => { e.stopPropagation(); updateData('jobName', e.target.value) }}
              onClick={(e) => e.stopPropagation()}
              className="w-full text-sm font-semibold text-white bg-transparent border-b border-transparent hover:border-gray-600 focus:border-white focus:outline-none truncate"
              placeholder="작업 이름 입력..."
            />
          </div>
          {hasStartConditions && (
            <div className="flex items-center gap-1 px-1.5 py-0.5 bg-cyan-500/20 rounded flex-shrink-0">
              <Filter className="w-2.5 h-2.5 text-cyan-400" />
              <span className="text-[9px] text-cyan-400">{startStates.length}</span>
            </div>
          )}
        </div>

        <div className="px-3 pb-2 flex items-center gap-2">
          <input
            type="text"
            value={data.server || data.subtype || ''}
            onChange={(e) => { e.stopPropagation(); updateData('server', e.target.value) }}
            onClick={(e) => e.stopPropagation()}
            className="flex-1 min-w-0 text-[9px] font-mono text-gray-400 bg-transparent border-b border-transparent hover:border-gray-600 focus:border-white focus:outline-none truncate"
            placeholder="{namespace}/action_server"
            title="Action Server. {namespace}는 배포 시 에이전트의 namespace로 치환됩니다."
          />
          {data.actionType && (
            <span className="text-[8px] px-1 py-0.5 rounded truncate flex-shrink-0" style={{ backgroundColor: `${color}30`, color }}>
              {data.actionType.split('/').pop()}
            </span>
          )}
        </div>

        {/* Auto-Generate States Toggle */}
        <div className="px-3 pb-2">
          <label className="flex items-center gap-2 cursor-pointer group" onClick={(e) => e.stopPropagation()}>
            <input
              type="checkbox"
              checked={autoGenerateStates}
              onChange={(e) => { e.stopPropagation(); toggleAutoGenerateStates(e.target.checked) }}
              onClick={(e) => e.stopPropagation()}
              className="w-3.5 h-3.5 rounded border-gray-500 bg-elevated text-purple-500 focus:ring-purple-500 focus:ring-offset-0"
            />
            <Sparkles className="w-3 h-3 text-purple-400" />
            <span className="text-[10px] text-purple-400 group-hover:text-purple-300">상태 자동 생성</span>
          </label>
          {autoGenerateStates && jobName.trim() && (
            <div className="mt-1 ml-5 flex flex-wrap gap-1">
              {autoGeneratedStates.slice(0, 3).map(s => (
                <span key={s.code} className="text-[8px] px-1.5 py-0.5 rounded" style={{ backgroundColor: `${s.color}20`, color: s.color }}>
                  {s.code}
                </span>
              ))}
              {autoGeneratedStates.length > 3 && <span className="text-[8px] text-gray-500">+{autoGeneratedStates.length - 3}</span>}
            </div>
          )}
          {autoGenerateStates && !jobName.trim() && (
            <p className="mt-1 ml-5 text-[9px] text-yellow-500/70">작업 이름을 입력하면 상태가 자동 생성됩니다</p>
          )}
        </div>
      </div>

      {/* Goal Parameters Section */}
      <GoalParametersSection
        isExpanded={expandedSection === 'params'}
        onToggle={() => setExpandedSection(expandedSection === 'params' ? null : 'params')}
        isLoadingFields={isLoadingFields}
        goalFields={goalFields}
        params={params}
        fieldSources={fieldSources}
        availableSteps={availableSteps}
        hasActionType={!!data.actionType}
        onUpdateParam={updateParam}
        onUpdateFieldSource={updateFieldSource}
      />

      {/* Result Schema Section */}
      <div className="border-b border-primary">
        <button
          onClick={(e) => { e.stopPropagation(); setExpandedSection(expandedSection === 'result' ? null : 'result') }}
          className="w-full px-3 py-1.5 flex items-center justify-between hover:bg-elevated/50 transition-colors"
        >
          <div className="flex items-center gap-2">
            <Download className="w-3 h-3 text-green-500" />
            <span className="text-[10px] text-green-400 uppercase tracking-wider font-medium">Result 스키마</span>
            {isLoadingFields ? <Loader2 className="w-3 h-3 text-green-500 animate-spin" /> : <span className="text-[9px] text-gray-600">({resultFields.length})</span>}
          </div>
          {expandedSection === 'result' ? <ChevronUp className="w-3 h-3 text-gray-500" /> : <ChevronDown className="w-3 h-3 text-gray-500" />}
        </button>
        {expandedSection === 'result' && (
          <div className="px-3 pb-2 space-y-2">
            {resultFields.length === 0 ? (
              <div className="p-2 bg-elevated rounded border border-gray-700">
                <p className="text-[9px] text-gray-500">Result 스키마 없음</p>
              </div>
            ) : (
              <div className="space-y-1">
                {resultFields.map((field) => (
                  <div key={field.name} className="flex items-center justify-between px-2 py-1.5 bg-surface rounded border border-green-500/20">
                    <span className="text-[9px] text-green-400 font-mono">{field.name}</span>
                    <code className="text-[8px] text-purple-400 bg-purple-500/10 px-1.5 py-0.5 rounded">${'{'}${jobName || id}.{field.name}{'}'}</code>
                  </div>
                ))}
              </div>
            )}
          </div>
        )}
      </div>

      {/* Start Conditions Section */}
      <div className="border-b border-primary">
        <button
          onClick={(e) => { e.stopPropagation(); setExpandedSection(expandedSection === 'start' ? null : 'start') }}
          className="w-full px-3 py-1.5 flex items-center justify-between hover:bg-elevated/50 transition-colors"
        >
          <div className="flex items-center gap-2">
            <div className="w-2 h-2 rounded-full bg-cyan-500" />
            <span className="text-[10px] text-cyan-400 uppercase tracking-wider font-medium">시작 조건</span>
            <span className="text-[9px] text-gray-600">({startStates.length})</span>
          </div>
          {expandedSection === 'start' ? <ChevronUp className="w-3 h-3 text-gray-500" /> : <ChevronDown className="w-3 h-3 text-gray-500" />}
        </button>
        {expandedSection === 'start' && (
          <div className="px-3 pb-2 space-y-1.5">
            {startStates.map((ss, idx) => (
              <div key={ss.id} className="flex flex-wrap items-center gap-1 text-[9px] bg-cyan-500/10 px-2 py-1.5 rounded group">
                {idx > 0 && (
                  <select value={ss.operator || 'and'} onChange={(e) => { e.stopPropagation(); updateStartStateField(ss.id, 'operator', e.target.value as 'and' | 'or') }} onClick={(e) => e.stopPropagation()} className="bg-surface text-[9px] text-orange-400 font-bold uppercase focus:outline-none cursor-pointer rounded px-1.5 py-0.5 border border-orange-500/30">
                    <option value="and">AND</option>
                    <option value="or">OR</option>
                  </select>
                )}
                <select value={ss.quantifier || 'self'} onChange={(e) => { e.stopPropagation(); updateStartStateField(ss.id, 'quantifier', e.target.value) }} onClick={(e) => e.stopPropagation()} className="bg-surface text-[9px] text-purple-400 font-medium focus:outline-none cursor-pointer rounded px-1.5 py-0.5 border border-purple-500/30">
                  <option value="self">Self</option>
                  <option value="every">Every</option>
                  <option value="any">Any</option>
                  <option value="specific">Agent</option>
                </select>
                {(ss.quantifier === 'every' || ss.quantifier === 'any' || ss.quantifier === 'specific') && (
                  <select value={ss.agentId || ''} onChange={(e) => { e.stopPropagation(); updateStartStateField(ss.id, 'agentId', e.target.value) }} onClick={(e) => e.stopPropagation()} className="bg-surface text-[9px] text-blue-400 focus:outline-none cursor-pointer rounded px-1.5 py-0.5 border border-blue-500/30 max-w-[80px] truncate">
                    {availableAgents.length === 0 && <option value="">No agents</option>}
                    {availableAgents.map(agent => <option key={agent.id} value={agent.id}>{agent.name}</option>)}
                  </select>
                )}
                <span className="text-gray-500">is</span>
                <select value={ss.state} onChange={(e) => { e.stopPropagation(); updateStartStateField(ss.id, 'state', e.target.value) }} onClick={(e) => e.stopPropagation()} className="bg-surface text-[9px] text-cyan-400 font-mono focus:outline-none cursor-pointer rounded px-1.5 py-0.5 border border-cyan-500/30 max-w-[70px] truncate">
                  {states.map(s => <option key={s} value={s}>{s}</option>)}
                </select>
                <button onClick={(e) => { e.stopPropagation(); removeStartState(ss.id) }} className="ml-auto opacity-0 group-hover:opacity-100 transition-opacity">
                  <X className="w-2.5 h-2.5 text-cyan-500/70 hover:text-red-400" />
                </button>
              </div>
            ))}
            <button onClick={(e) => { e.stopPropagation(); addStartState() }} className="text-[9px] text-cyan-400 hover:text-cyan-300">+ 시작 조건 추가</button>
          </div>
        )}
      </div>

      {/* During States Section */}
      <div className="px-3 py-2 border-b border-primary">
        <div className="flex items-center justify-between mb-1.5">
          <div className="flex items-center gap-2">
            <div className="w-2 h-2 rounded-full bg-yellow-500 animate-pulse" />
            <span className="text-[10px] text-yellow-400 uppercase tracking-wider font-medium">실행 중 상태</span>
          </div>
          <button onClick={(e) => { e.stopPropagation(); addDuringState() }} className="p-0.5 hover:bg-yellow-500/20 rounded transition-colors">
            <Plus className="w-2.5 h-2.5 text-yellow-500" />
          </button>
        </div>
        <div className="flex flex-wrap gap-1">
          {duringStateTargets.length === 0 ? (
            <span className="text-[9px] text-gray-600 italic">실행 중 상태 없음</span>
          ) : (
            duringStateTargets.map((target, i) => (
              <div key={i} className="flex items-center gap-1 px-2 py-0.5 bg-yellow-500/10 border border-yellow-500/30 rounded-full group">
                <select value={target.state} onChange={(e) => { e.stopPropagation(); const next = [...duringStateTargets]; next[i] = { ...next[i], state: e.target.value }; updateData('duringStateTargets', next) }} onClick={(e) => e.stopPropagation()} className="bg-elevated text-[9px] text-yellow-400 font-medium focus:outline-none cursor-pointer rounded px-1">
                  {states.map(s => <option key={s} value={s}>{s}</option>)}
                </select>
                <select value={target.target_type || 'self'} onChange={(e) => { e.stopPropagation(); const next = [...duringStateTargets]; const nextTarget: NormalizedDuringStateTarget = { ...next[i], target_type: e.target.value as NormalizedDuringStateTarget['target_type'] }; if (nextTarget.target_type !== 'agent') nextTarget.agent_id = undefined; else if (!nextTarget.agent_id && availableAgents.length > 0) nextTarget.agent_id = availableAgents[0].id; next[i] = nextTarget; updateData('duringStateTargets', next) }} onClick={(e) => e.stopPropagation()} className="bg-elevated text-[9px] text-yellow-300 font-medium focus:outline-none cursor-pointer rounded px-1">
                  {DURING_TARGET_OPTIONS.map(option => <option key={option.value} value={option.value}>{option.label}</option>)}
                </select>
                {target.target_type === 'agent' && (
                  <select value={target.agent_id || ''} onChange={(e) => { e.stopPropagation(); const next = [...duringStateTargets]; next[i] = { ...next[i], agent_id: e.target.value }; updateData('duringStateTargets', next) }} onClick={(e) => e.stopPropagation()} className="bg-elevated text-[9px] text-yellow-300 font-medium focus:outline-none cursor-pointer rounded px-1">
                    {availableAgents.length === 0 && <option value="">No agents</option>}
                    {availableAgents.map(agent => <option key={agent.id} value={agent.id}>{agent.name}</option>)}
                  </select>
                )}
                <button onClick={(e) => { e.stopPropagation(); updateData('duringStateTargets', duringStateTargets.filter((_, idx) => idx !== i)) }} className="opacity-0 group-hover:opacity-100 transition-opacity">
                  <X className="w-2.5 h-2.5 text-yellow-500/70 hover:text-yellow-500" />
                </button>
              </div>
            ))
          )}
        </div>
      </div>

      {/* End States Section with Handles */}
      <div className="px-3 py-2 relative">
        <div className="flex items-center justify-between mb-1.5">
          <div className="flex items-center gap-2">
            <div className="w-2 h-2 rounded-sm bg-gradient-to-r from-green-500 to-red-500" />
            <span className="text-[10px] text-gray-300 uppercase tracking-wider font-medium">종료 상태</span>
          </div>
          <button onClick={(e) => { e.stopPropagation(); addEndState() }} className="p-0.5 hover:bg-gray-500/20 rounded transition-colors">
            <Plus className="w-2.5 h-2.5 text-gray-400" />
          </button>
        </div>

        <div className="space-y-1.5">
          {endStates.map((endState) => {
            const outcome = endState.outcome || inferOutcomeFromEndState(endState)
            const stateColor = endState.color || getEndStateColor(endState)
            return (
              <div key={endState.id} className="flex items-center gap-1.5 pr-5 relative group">
                <div className="w-2.5 h-2.5 rounded-full flex-shrink-0 border" style={{ backgroundColor: stateColor, borderColor: `${stateColor}99` }} />
                <select value={outcome} onChange={(e) => { e.stopPropagation(); updateEndState(endState.id, 'outcome', e.target.value) }} onClick={(e) => e.stopPropagation()} className="w-14 px-1 py-0.5 bg-surface border border-gray-700 rounded text-[9px] text-gray-300 focus:outline-none cursor-pointer">
                  {OUTCOME_OPTIONS.map(option => <option key={option.value} value={option.value}>{option.label}</option>)}
                </select>
                <span className="text-[9px] text-gray-600">→</span>
                <select value={endState.state} onChange={(e) => { e.stopPropagation(); updateEndState(endState.id, 'state', e.target.value) }} onClick={(e) => e.stopPropagation()} className="flex-1 px-1 py-0.5 bg-surface border border-gray-700 rounded text-[9px] focus:outline-none cursor-pointer" style={{ color: stateColor }}>
                  {states.map(s => <option key={s} value={s}>{s}</option>)}
                </select>
                {endStates.length > 1 && (
                  <button onClick={(e) => { e.stopPropagation(); removeEndState(endState.id) }} className="absolute right-0 text-gray-600 hover:text-red-400 transition-colors opacity-0 group-hover:opacity-100">
                    <X className="w-3 h-3" />
                  </button>
                )}
              </div>
            )
          })}
        </div>

        {/* Output Handles - inline labels */}
        <div className="absolute right-[-12px] top-0 bottom-0 flex flex-col justify-center gap-0.5 py-6">
          <div className="flex items-center h-5" title="성공">
            <span className="text-[7px] text-green-400 mr-1">S</span>
            <Handle type="source" position={Position.Right} id="success" className="!w-3 !h-3 !border-2 !rounded-full hover:!w-4 hover:!h-4 transition-all cursor-crosshair !pointer-events-auto !relative !transform-none !top-auto !right-auto" style={{ backgroundColor: '#22c55e', borderColor: '#22c55e99' }} />
          </div>
          <div className="flex items-center h-5" title="실패">
            <span className="text-[7px] text-red-400 mr-1">F</span>
            <Handle type="source" position={Position.Right} id="failed" className="!w-3 !h-3 !border-2 !rounded-full hover:!w-4 hover:!h-4 transition-all cursor-crosshair !pointer-events-auto !relative !transform-none !top-auto !right-auto" style={{ backgroundColor: '#ef4444', borderColor: '#ef444499' }} />
          </div>
          <div className="flex items-center h-5" title="중단">
            <span className="text-[7px] text-red-400 mr-1">A</span>
            <Handle type="source" position={Position.Right} id="aborted" className="!w-3 !h-3 !border-2 !rounded-full hover:!w-4 hover:!h-4 transition-all cursor-crosshair !pointer-events-auto !relative !transform-none !top-auto !right-auto" style={{ backgroundColor: '#ef4444', borderColor: '#ef444499' }} />
          </div>
          <div className="flex items-center h-5" title="취소">
            <span className="text-[7px] text-gray-400 mr-1">C</span>
            <Handle type="source" position={Position.Right} id="cancelled" className="!w-3 !h-3 !border-2 !rounded-full hover:!w-4 hover:!h-4 transition-all cursor-crosshair !pointer-events-auto !relative !transform-none !top-auto !right-auto" style={{ backgroundColor: '#6b7280', borderColor: '#6b728099' }} />
          </div>
        </div>
      </div>

      {/* Footer */}
      <div className="px-3 py-1 border-t border-primary flex items-center justify-between" style={{ backgroundColor: '#16162a' }}>
        <span className="text-[9px] text-gray-500 font-mono truncate max-w-[180px]">{data.server || data.subtype}</span>
        <div className="w-1.5 h-1.5 rounded-full bg-green-500" />
      </div>
    </div>
  )
})

StateActionNode.displayName = 'StateActionNode'

export default StateActionNode
