import { memo, useState, useEffect, useMemo } from 'react'
import { Handle, Position, NodeProps, useReactFlow, useUpdateNodeInternals, useNodes } from 'reactflow'
import { ChevronDown, ChevronUp, Plus, X, Filter, Loader2, Sparkles, Download, Upload } from 'lucide-react'
import type { StartStateConfig, EndStateConfig, ActionField, ActionOutcome, DuringStateTarget, GraphState, ParameterFieldSource } from '../../../types'
import { capabilityApi } from '../../../api/client'
import ParameterSourceSelector from '../../../components/ParameterSourceSelector'

// Auto-generated state suffixes
const AUTO_STATE_SUFFIXES = {
  during: '_during',
  succeed: '_succeed',
  failed: '_failed',
  aborted: '_aborted',
  cancelled: '_cancelled',
  timeout: '_timeout',
} as const

// Generate states from node name
const generateStatesFromNodeName = (nodeName: string): {
  during: string
  succeed: string
  failed: string
  aborted: string
  cancelled: string
  timeout: string
} => {
  // Sanitize node name: lowercase, replace spaces with underscores
  const sanitized = nodeName.toLowerCase().replace(/\s+/g, '_').replace(/[^a-z0-9_]/g, '')
  return {
    during: `${sanitized}${AUTO_STATE_SUFFIXES.during}`,
    succeed: `${sanitized}${AUTO_STATE_SUFFIXES.succeed}`,
    failed: `${sanitized}${AUTO_STATE_SUFFIXES.failed}`,
    aborted: `${sanitized}${AUTO_STATE_SUFFIXES.aborted}`,
    cancelled: `${sanitized}${AUTO_STATE_SUFFIXES.cancelled}`,
    timeout: `${sanitized}${AUTO_STATE_SUFFIXES.timeout}`,
  }
}

// Create GraphState objects from auto-generated states
const createAutoGeneratedGraphStates = (nodeName: string, stepId: string): GraphState[] => {
  const states = generateStatesFromNodeName(nodeName)
  return [
    { code: states.during, name: `${nodeName} (During)`, type: 'graph', step_id: stepId, phase: 'executing', color: '#EAB308', semantic_tags: ['executing', 'busy', nodeName.toLowerCase()] },
    { code: states.succeed, name: `${nodeName} (Success)`, type: 'graph', step_id: stepId, phase: 'success', color: '#22C55E', semantic_tags: ['success', 'completed', nodeName.toLowerCase()] },
    { code: states.failed, name: `${nodeName} (Failed)`, type: 'graph', step_id: stepId, phase: 'failed', color: '#EF4444', semantic_tags: ['failed', 'error', nodeName.toLowerCase()] },
    { code: states.aborted, name: `${nodeName} (Aborted)`, type: 'graph', step_id: stepId, phase: 'failed', color: '#EF4444', semantic_tags: ['aborted', 'error', nodeName.toLowerCase()] },
    { code: states.cancelled, name: `${nodeName} (Cancelled)`, type: 'graph', step_id: stepId, phase: 'failed', color: '#6B7280', semantic_tags: ['cancelled', nodeName.toLowerCase()] },
    { code: states.timeout, name: `${nodeName} (Timeout)`, type: 'graph', step_id: stepId, phase: 'failed', color: '#F59E0B', semantic_tags: ['timeout', 'error', nodeName.toLowerCase()] },
  ]
}

export { generateStatesFromNodeName, createAutoGeneratedGraphStates, AUTO_STATE_SUFFIXES }

// Convert capability goal_schema to ActionField format
const schemaToFields = (schema: Record<string, unknown> | null): ActionField[] => {
  if (!schema) return []

  const fields: ActionField[] = []

  // Check if this is a JSON Schema format (has "type": "object" and "properties")
  if (schema.type === 'object' && schema.properties && typeof schema.properties === 'object') {
    // JSON Schema format: { "type": "object", "properties": { "field": {...} }, ... }
    const properties = schema.properties as Record<string, unknown>
    for (const [name, fieldInfo] of Object.entries(properties)) {
      if (typeof fieldInfo === 'object' && fieldInfo !== null) {
        const info = fieldInfo as Record<string, unknown>
        fields.push({
          name,
          type: (info.type as string) || 'string',
          default: info.default as string | undefined,
          is_array: Boolean(info.is_array),
          is_constant: false,
        })
      } else if (typeof fieldInfo === 'string') {
        fields.push({
          name,
          type: fieldInfo,
          is_array: false,
          is_constant: false,
        })
      }
    }
    return fields
  }

  // Legacy/simple ROS2 message schema format
  // Schema format: { "field_name": { "type": "ros2_type", ... }, ... }
  // Skip metadata fields
  const metadataFields = ['type', 'properties', 'x-ros-name', 'x-ros-namespace', 'required', 'additionalProperties']

  for (const [name, fieldInfo] of Object.entries(schema)) {
    // Skip JSON Schema metadata fields
    if (metadataFields.includes(name)) continue

    if (typeof fieldInfo === 'object' && fieldInfo !== null) {
      const info = fieldInfo as Record<string, unknown>
      fields.push({
        name,
        type: (info.type as string) || 'string',
        default: info.default as string | undefined,
        is_array: Boolean(info.is_array),
        is_constant: false,
      })
    } else if (typeof fieldInfo === 'string') {
      // Simple format: { "field_name": "type" }
      fields.push({
        name,
        type: fieldInfo,
        is_array: false,
        is_constant: false,
      })
    }
  }

  return fields
}

// Map ROS2 types to input types
type InputType = 'number' | 'text' | 'checkbox' | 'pose' | 'trajectory' | 'complex'

const getInputType = (rosType: string, isArray: boolean): InputType => {
  const numericTypes = ['int8', 'int16', 'int32', 'int64', 'uint8', 'uint16', 'uint32', 'uint64', 'float32', 'float64', 'double']

  // Check for complex ROS2 message types (contain '/')
  if (rosType.includes('/')) {
    const lowerType = rosType.toLowerCase()
    // Pose-related types
    if (lowerType.includes('pose') || lowerType.includes('point') || lowerType.includes('transform')) {
      return 'pose'
    }
    // Trajectory types
    if (lowerType.includes('trajectory') || lowerType.includes('jointtrajectory')) {
      return 'trajectory'
    }
    // Other complex types
    return 'complex'
  }

  if (rosType === 'bool') return 'checkbox'
  if (numericTypes.some(t => rosType === t)) return 'number'
  if (rosType === 'string') return 'text'

  // Arrays of primitives
  if (isArray) return 'complex'

  return 'text'
}

// Color palette for end states
const OUTCOME_COLORS: Record<ActionOutcome, string> = {
  success: '#22c55e',
  failed: '#ef4444',
  aborted: '#ef4444',
  cancelled: '#6b7280',
  timeout: '#f59e0b',
  rejected: '#ef4444',
}

const OUTCOME_HANDLE_IDS: Record<ActionOutcome, string> = {
  success: 'success',
  failed: 'failed',
  aborted: 'aborted',
  cancelled: 'cancelled',
  timeout: 'timeout',
  rejected: 'failed',
}

const END_STATE_COLORS: Record<string, string> = {
  success: '#22c55e',
  completed: '#22c55e',
  idle: '#22c55e',
  error: '#ef4444',
  failed: '#ef4444',
  timeout: '#f59e0b',
  partial: '#eab308',
  cancelled: '#6b7280',
}

const OUTCOME_OPTIONS: Array<{ value: ActionOutcome; label: string }> = [
  { value: 'success', label: 'Success' },
  { value: 'failed', label: 'Failed' },
  { value: 'aborted', label: 'Aborted' },
  { value: 'cancelled', label: 'Cancelled' },
  { value: 'timeout', label: 'Timeout' },
  { value: 'rejected', label: 'Rejected' },
]

const DURING_TARGET_OPTIONS: Array<{ value: NonNullable<DuringStateTarget['target_type']>; label: string }> = [
  { value: 'self', label: 'Self' },
  { value: 'all', label: 'All' },
  { value: 'agent', label: 'Agent' },
]

const normalizeOutcomeValue = (value?: string): ActionOutcome | undefined => {
  if (!value) return undefined
  const lower = value.toLowerCase()
  if (lower === 'success' || lower === 'succeeded') return 'success'
  if (lower === 'failed' || lower === 'failure' || lower === 'error') return 'failed'
  if (lower === 'aborted' || lower === 'abort') return 'aborted'
  if (lower === 'cancelled' || lower === 'canceled' || lower === 'cancel') return 'cancelled'
  if (lower === 'timeout' || lower === 'timed_out') return 'timeout'
  if (lower === 'rejected') return 'rejected'
  return undefined
}

const inferOutcomeFromEndState = (endState: EndStateConfig): ActionOutcome => {
  const label = (endState.label || '').toLowerCase()
  const stateValue = (endState.state || '').toLowerCase()

  if (label.includes('timeout') || stateValue.includes('timeout')) return 'timeout'
  if (label.includes('cancel') || stateValue.includes('cancel')) return 'cancelled'
  if (label.includes('abort') || stateValue.includes('abort')) return 'aborted'
  if (label.includes('fail') || label.includes('error') || stateValue.includes('fail') || stateValue.includes('error')) return 'failed'
  if (label.includes('success') || label.includes('complete') || stateValue.includes('idle') || stateValue.includes('ready')) return 'success'
  return 'success'
}

const getEndStateColor = (endState: EndStateConfig): string => {
  if (endState.color) {
    return endState.color
  }
  if (endState.outcome && OUTCOME_COLORS[endState.outcome]) {
    return OUTCOME_COLORS[endState.outcome]
  }
  if (endState.label) {
    const lowerLabel = endState.label.toLowerCase()
    if (lowerLabel.includes('success') || lowerLabel.includes('complete')) return '#22c55e'
    if (lowerLabel.includes('error') || lowerLabel.includes('fail') || lowerLabel.includes('abort')) return '#ef4444'
    if (lowerLabel.includes('timeout')) return '#f59e0b'
  }
  return END_STATE_COLORS[endState.state.toLowerCase()] || '#6b7280'
}

interface StateActionNodeData {
  label: string
  subtype: string
  color: string
  actionType?: string
  server?: string
  // Job configuration
  jobName?: string
  params?: Record<string, unknown>
  fieldSources?: Record<string, ParameterFieldSource>  // Per-field source configuration
  // Result fields from this action (for other nodes to reference)
  resultFields?: Array<{ name: string; type: string }>
  // Auto-generate states toggle
  autoGenerateStates?: boolean
  generatedStates?: GraphState[]  // Stores the auto-generated states
  // New State ActionGraph Configuration
  startStates?: StartStateConfig[]
  duringStates?: string[]
  duringStateTargets?: DuringStateTarget[]
  endStates?: EndStateConfig[]
  // Available data
  availableStates?: string[]
  availableAgents?: Array<{ id: string; name: string }>
  availableWaypoints?: Array<{ id: string; name: string }>
}

type NormalizedDuringStateTarget = {
  state: string
  target_type: NonNullable<DuringStateTarget['target_type']>
  agent_id?: string
}

const StateActionNode = memo(({ id, data, selected }: NodeProps<StateActionNodeData>) => {
  const color = data.color || '#3b82f6'
  const { setNodes, setEdges } = useReactFlow()
  const updateNodeInternals = useUpdateNodeInternals()
  const allNodes = useNodes()
  const baseStates = data.availableStates || []
  const [expandedSection, setExpandedSection] = useState<string | null>(null)

  // Action fields from API
  const [goalFields, setGoalFields] = useState<ActionField[]>([])
  const [resultFields, setResultFields] = useState<ActionField[]>([])
  const [isLoadingFields, setIsLoadingFields] = useState(false)

  // Auto-generate states (default: enabled)
  const autoGenerateStates = data.autoGenerateStates ?? true
  const jobName = data.jobName ?? ''

  // Compute auto-generated states when jobName changes
  const autoGeneratedStates = useMemo(() => {
    if (!autoGenerateStates || !jobName.trim()) return []
    return createAutoGeneratedGraphStates(jobName.trim(), id)
  }, [autoGenerateStates, jobName, id])

  // Combine base states with auto-generated ones
  const states = useMemo(() => {
    if (!autoGenerateStates || autoGeneratedStates.length === 0) return baseStates
    const autoStateCodes = autoGeneratedStates.map(s => s.code)
    return [...baseStates, ...autoStateCodes]
  }, [baseStates, autoGenerateStates, autoGeneratedStates])

  // Generate End States from result fields
  // ROS2 Action Server outcomes: SUCCEEDED, ABORTED, CANCELED
  const generateEndStatesFromResults = (results: ActionField[]): EndStateConfig[] => {
    const endStates: EndStateConfig[] = []
    const now = Date.now()

    // Find appropriate states from available states
    const successState = states.includes('idle') ? 'idle' :
                         states.includes('completed') ? 'completed' : states[0] || 'idle'
    const errorState = states.includes('error') ? 'error' :
                       states.includes('failed') ? 'failed' : states[0] || 'error'

    // 1. SUCCESS - Always present (SUCCEEDED)
    endStates.push({
      id: `end-success-${now}`,
      state: successState,
      label: 'Success',
      outcome: 'success',
      color: OUTCOME_COLORS.success,
    })

    // 2. ABORTED/FAILURE - Always present (action can always fail)
    endStates.push({
      id: `end-failed-${now + 1}`,
      state: errorState,
      label: 'Failed',
      outcome: 'failed',
      color: OUTCOME_COLORS.failed,
    })

    endStates.push({
      id: `end-aborted-${now + 2}`,
      state: errorState,
      label: 'Aborted',
      outcome: 'aborted',
      color: OUTCOME_COLORS.aborted,
    })

    // 3. Check result fields for additional specific outcomes
    const hasErrorCode = results.some(f =>
      f.name.includes('error_code') || f.name.includes('result_code') || f.name.includes('error_id')
    )
    const hasTimeout = results.some(f =>
      f.name.includes('timeout') || f.name.includes('timed_out')
    )

    // Add specific error states if result fields suggest them
    if (hasErrorCode) {
      // If there's an error code, we might have specific error types
      endStates.push({
        id: `end-error-${now + 3}`,
        state: errorState,
        label: 'Error',
        outcome: 'failed',
        color: '#dc2626',
      })
    }

    if (hasTimeout) {
      endStates.push({
        id: `end-timeout-${now + 4}`,
        state: errorState,
        label: 'Timeout',
        outcome: 'timeout',
        color: OUTCOME_COLORS.timeout,
      })
    }

    // 4. CANCELED - Optional but common (client cancellation)
    endStates.push({
      id: `end-cancelled-${now + 5}`,
      state: states.includes('cancelled') ? 'cancelled' : errorState,
      label: 'Cancelled',
      outcome: 'cancelled',
      color: OUTCOME_COLORS.cancelled,
    })

    return endStates
  }

  // Fetch action schema from discovered capabilities
  useEffect(() => {
    if (!data.actionType) {
      setGoalFields([])
      setResultFields([])
      return
    }

    setIsLoadingFields(true)

    // Get schema from discovered capabilities
    capabilityApi.getByActionType(data.actionType)
      .then((capData) => {
        if (capData.agents && capData.agents.length > 0) {
          // Use schema from first agent with this capability
          const firstAgent = capData.agents[0]
          const goalFields = schemaToFields(firstAgent.goal_schema)
          setGoalFields(goalFields)

          // Parse result_schema and store in both state and node data
          const resultFieldsParsed = schemaToFields(firstAgent.result_schema)
          setResultFields(resultFieldsParsed)

          // Store resultFields in node data so other nodes can access them
          const resultFieldsForData = resultFieldsParsed.map(f => ({
            name: f.name,
            type: f.type + (f.is_array ? '[]' : '')
          }))
          updateData('resultFields', resultFieldsForData)

          // Auto-generate basic End States
          if (!data.endStates || data.endStates.length === 0) {
            const autoEndStates = generateEndStatesFromResults(resultFieldsParsed)
            updateData('endStates', autoEndStates)
          }
        } else {
          setGoalFields([])
          setResultFields([])
          updateData('resultFields', [])
        }
      })
      .catch((err) => {
        console.error('Failed to fetch capability schema:', err)
        setGoalFields([])
        setResultFields([])
        updateData('resultFields', [])
      })
      .finally(() => {
        setIsLoadingFields(false)
      })
  }, [data.actionType])

  // Auto-expand params section when no schema available and node is selected
  useEffect(() => {
    if (selected && !isLoadingFields && goalFields.length === 0 && data.actionType) {
      setExpandedSection('params')
    }
  }, [selected, isLoadingFields, goalFields.length, data.actionType])

  // State configurations with defaults
  const startStates = data.startStates || []
  const duringStateTargets: NormalizedDuringStateTarget[] = (data.duringStateTargets && data.duringStateTargets.length > 0)
    ? data.duringStateTargets.map(target => ({
      ...target,
      target_type: (target.target_type || 'self') as NormalizedDuringStateTarget['target_type'],
    }))
    : (data.duringStates || [])
      .filter(Boolean)
      .slice(0, 1)
      .map(state => ({ state, target_type: 'self' as const }))
  const endStates = data.endStates || []

  const updateData = (field: string, value: unknown) => {
    setNodes((nds) => nds.map((n) =>
      n.id === id ? { ...n, data: { ...n.data, [field]: value } } : n
    ))
  }

  // Auto-apply generated states when toggle is enabled and jobName exists
  const applyAutoGeneratedStates = () => {
    if (!jobName.trim()) return

    const generatedStates = generateStatesFromNodeName(jobName.trim())

    // Update during states
    const newDuringTargets: DuringStateTarget[] = [
      { state: generatedStates.during, target_type: 'self' }
    ]

    // Update end states with auto-generated state codes
    // Use stable IDs (not Date.now()) so ReactFlow can track handles properly
    const existingEndStates = data.endStates || []
    const existingByOutcome = new Map<ActionOutcome, EndStateConfig>()
    const handleIdRemap = new Map<string, string>()

    existingEndStates.forEach((endState) => {
      const inferred = normalizeOutcomeValue(endState.outcome) || inferOutcomeFromEndState(endState)
      const handleId = OUTCOME_HANDLE_IDS[inferred]
      if (handleId && endState.id !== handleId) {
        handleIdRemap.set(endState.id, handleId)
      }
      if (!existingByOutcome.has(inferred)) {
        existingByOutcome.set(inferred, endState)
      }
    })

    const buildEndState = (outcome: ActionOutcome, state: string, label: string, color: string): EndStateConfig => {
      const existing = existingByOutcome.get(outcome)
      return {
        ...existing,
        id: OUTCOME_HANDLE_IDS[outcome],
        state,
        label: existing?.label || label,
        outcome,
        color: existing?.color || color,
      }
    }

    const newEndStates: EndStateConfig[] = [
      buildEndState('success', generatedStates.succeed, 'Success', '#22C55E'),
      buildEndState('failed', generatedStates.failed, 'Failed', '#EF4444'),
      buildEndState('aborted', generatedStates.aborted, 'Aborted', '#EF4444'),
      buildEndState('cancelled', generatedStates.cancelled, 'Cancelled', '#6B7280'),
      buildEndState('timeout', generatedStates.timeout, 'Timeout', '#F59E0B'),
    ]

    // Store generated GraphState objects for saving
    const graphStates = createAutoGeneratedGraphStates(jobName.trim(), id)

    setNodes((nds) => nds.map((n) =>
      n.id === id ? {
        ...n,
        data: {
          ...n.data,
          duringStateTargets: newDuringTargets,
          endStates: newEndStates,
          generatedStates: graphStates,
        }
      } : n
    ))

    if (handleIdRemap.size > 0) {
      setEdges((eds) => eds.map((edge) => {
        if (edge.source !== id || !edge.sourceHandle) return edge
        const mapped = handleIdRemap.get(edge.sourceHandle)
        if (!mapped || mapped === edge.sourceHandle) return edge
        return { ...edge, sourceHandle: mapped }
      }))
    }
  }

  // Toggle auto-generate states
  const toggleAutoGenerateStates = (enabled: boolean) => {
    updateData('autoGenerateStates', enabled)
    if (enabled && jobName.trim()) {
      // Apply states immediately when enabled
      setTimeout(() => applyAutoGeneratedStates(), 0)
    }
  }

  // Re-apply when jobName changes while auto-generate is enabled
  useEffect(() => {
    if (autoGenerateStates && jobName.trim()) {
      applyAutoGeneratedStates()
    }
  }, [jobName, autoGenerateStates])

  // CRITICAL: Update ReactFlow internals after node data changes
  // This ensures handles remain interactive after re-renders
  useEffect(() => {
    // Small delay to ensure DOM has updated
    const timer = setTimeout(() => {
      updateNodeInternals(id)
    }, 0)
    return () => clearTimeout(timer)
  }, [id, jobName, updateNodeInternals])

  // Available agent types for conditions
  const availableAgents = data.availableAgents || []

  // Job parameters
  const params = data.params || {}
  const fieldSources = data.fieldSources || {}

  // Get available steps (other action nodes that could provide results)
  const availableSteps = useMemo(() => {
    return allNodes
      .filter(node =>
        node.type === 'action' &&
        node.id !== id &&
        (node.data as StateActionNodeData)?.jobName
      )
      .map(node => {
        const nodeData = node.data as StateActionNodeData
        return {
          id: node.id,
          name: nodeData?.jobName || node.id,
          // Read resultFields from the other node's data (populated when their actionType is fetched)
          resultFields: nodeData?.resultFields || [],
        }
      })
  }, [allNodes, id])

  // Update job parameter
  const updateParam = (key: string, value: unknown) => {
    updateData('params', { ...params, [key]: value })
  }

  // Update field source configuration
  const updateFieldSource = (key: string, source: ParameterFieldSource | undefined) => {
    if (source === undefined) {
      // Remove field source (use constant value from params)
      const newFieldSources = { ...fieldSources }
      delete newFieldSources[key]
      updateData('fieldSources', Object.keys(newFieldSources).length > 0 ? newFieldSources : undefined)
    } else {
      updateData('fieldSources', { ...fieldSources, [key]: source })
    }
  }

  // Add new start state
  const addStartState = () => {
    const newStartState: StartStateConfig = {
      id: `start-${Date.now()}`,
      quantifier: 'self',
      state: states[0] || 'idle',
      operator: startStates.length > 0 ? 'and' : undefined,
    }
    updateData('startStates', [...startStates, newStartState])
  }

  // Remove start state
  const removeStartState = (startStateId: string) => {
    const filtered = startStates.filter(ss => ss.id !== startStateId)
    // Remove operator from first item if it exists
    if (filtered.length > 0 && filtered[0].operator) {
      filtered[0] = { ...filtered[0], operator: undefined }
    }
    updateData('startStates', filtered)
  }

  // Update start state field
  const updateStartStateField = (startStateId: string, field: keyof StartStateConfig, value: string | undefined) => {
    updateData('startStates', startStates.map((ss, idx) => {
      if (ss.id !== startStateId) return ss
      const updated = { ...ss, [field]: value }
      // If changing to 'self', clear agent
      if (field === 'quantifier' && value === 'self') {
        updated.agentId = undefined
      }
      // If changing to 'every' or 'any', set default agent
      if (field === 'quantifier' && (value === 'every' || value === 'any')) {
        if (!ss.agentId && availableAgents.length > 0) {
          updated.agentId = availableAgents[0].id
        }
      }
      // If changing to 'specific', set default agent
      if (field === 'quantifier' && value === 'specific') {
        if (!ss.agentId && availableAgents.length > 0) {
          updated.agentId = availableAgents[0].id
        }
      }
      // First item should not have operator
      if (idx === 0) {
        updated.operator = undefined
      }
      return updated
    }))
  }

  // Add new end state
  const addEndState = () => {
    const newEndState: EndStateConfig = {
      id: `end-${Date.now()}`,
      state: states[0] || 'idle',
      label: `State ${endStates.length + 1}`,
      outcome: 'success',
      color: OUTCOME_COLORS.success,
    }
    updateData('endStates', [...endStates, newEndState])
  }

  // Remove end state
  const removeEndState = (endStateId: string) => {
    if (endStates.length > 1) {
      updateData('endStates', endStates.filter(es => es.id !== endStateId))
    }
  }

  // Update end state
  const updateEndState = (endStateId: string, field: string, value: string) => {
    updateData('endStates', endStates.map(es => {
      if (es.id !== endStateId) return es
      const updated = { ...es, [field]: value }
      if (field === 'state' || field === 'label' || field === 'outcome') {
        updated.color = getEndStateColor(updated)
      }
      return updated
    }))
  }

  // Add during state
  const addDuringState = () => {
    if (states.length === 0) {
      return
    }
    updateData('duringStateTargets', [
      ...duringStateTargets,
      { state: states[0], target_type: 'self' },
    ])
  }

  const hasStartConditions = startStates.length > 0

	  return (
	    <div
	      className={`
	        relative min-w-[260px] max-w-[320px] rounded-lg overflow-visible
	        bg-[#1e1e2e] border-2
	        shadow-lg
	        ${selected ? 'border-white/60 shadow-xl shadow-blue-500/20' : 'border-[#2a2a4a]'}
	        transition-all duration-150
	      `}
	    >
	      {/* Header - Job Name (primary) & Action Server (secondary) */}
	      <div style={{ backgroundColor: `${color}25` }}>
	        {/* Job Name (primary - main title) */}
	        <div className="px-3 pt-2 pb-1 flex items-center gap-2">
          <div
            className="w-2 h-2 rounded-sm flex-shrink-0"
            style={{ backgroundColor: color }}
          />
          <div className="flex-1 min-w-0">
            <input
              type="text"
              value={jobName}
              onChange={(e) => {
                e.stopPropagation()
                updateData('jobName', e.target.value)
              }}
              onClick={(e) => e.stopPropagation()}
              className="w-full text-sm font-semibold text-white bg-transparent border-b border-transparent hover:border-gray-600 focus:border-white focus:outline-none truncate"
              placeholder="Enter job name..."
            />
          </div>
          {hasStartConditions && (
            <div className="flex items-center gap-1 px-1.5 py-0.5 bg-cyan-500/20 rounded flex-shrink-0">
              <Filter className="w-2.5 h-2.5 text-cyan-400" />
              <span className="text-[9px] text-cyan-400">{startStates.length}</span>
            </div>
          )}
        </div>
        {/* Action Server & Type (secondary info) */}
        <div className="px-3 pb-2 flex items-center gap-2">
          <span
            className="text-[9px] font-mono text-gray-400 truncate"
            title={data.server || data.subtype}
          >
            {(data.server || data.subtype).replace(/^\//, '')}
          </span>
          {data.actionType && (
            <span
              className="text-[8px] px-1 py-0.5 rounded truncate"
              style={{ backgroundColor: `${color}30`, color: color }}
              title={data.actionType}
            >
              {data.actionType.split('/').pop()}
            </span>
          )}
        </div>

        {/* Auto-Generate States Toggle */}
        <div className="px-3 pb-2">
          <label
            className="flex items-center gap-2 cursor-pointer group"
            onClick={(e) => e.stopPropagation()}
          >
            <input
              type="checkbox"
              checked={autoGenerateStates}
              onChange={(e) => {
                e.stopPropagation()
                toggleAutoGenerateStates(e.target.checked)
              }}
              onClick={(e) => e.stopPropagation()}
              className="w-3.5 h-3.5 rounded border-gray-500 bg-[#1a1a2e] text-purple-500 focus:ring-purple-500 focus:ring-offset-0"
            />
            <Sparkles className="w-3 h-3 text-purple-400" />
            <span className="text-[10px] text-purple-400 group-hover:text-purple-300">
              Auto-generate states
            </span>
          </label>
          {autoGenerateStates && jobName.trim() && (
            <div className="mt-1 ml-5 flex flex-wrap gap-1">
              {autoGeneratedStates.slice(0, 3).map(s => (
                <span
                  key={s.code}
                  className="text-[8px] px-1.5 py-0.5 rounded"
                  style={{ backgroundColor: `${s.color}20`, color: s.color }}
                >
                  {s.code}
                </span>
              ))}
              {autoGeneratedStates.length > 3 && (
                <span className="text-[8px] text-gray-500">+{autoGeneratedStates.length - 3}</span>
              )}
            </div>
          )}
          {autoGenerateStates && !jobName.trim() && (
            <p className="mt-1 ml-5 text-[9px] text-yellow-500/70">
              Enter job name to generate states
            </p>
          )}
        </div>
      </div>

      {/* Goal Parameters Section - Input parameters for ROS2 Action */}
      <div className="border-b border-[#2a2a4a]">
        <button
          onClick={(e) => { e.stopPropagation(); setExpandedSection(expandedSection === 'params' ? null : 'params') }}
          className="w-full px-3 py-1.5 flex items-center justify-between hover:bg-[#2a2a4a]/50 transition-colors"
        >
          <div className="flex items-center gap-2">
            <Upload className="w-3 h-3 text-amber-500" />
            <span className="text-[10px] text-amber-400 uppercase tracking-wider font-medium">Goal Parameters</span>
            <span className="text-[8px] text-gray-600 italic">→ Send</span>
            {isLoadingFields ? (
              <Loader2 className="w-3 h-3 text-amber-500 animate-spin" />
            ) : goalFields.length > 0 ? (
              <span className="text-[9px] text-gray-600">({goalFields.length})</span>
            ) : Object.keys(fieldSources).length > 0 ? (
              <span className="text-[9px] text-purple-500">({Object.keys(fieldSources).length} mapped)</span>
            ) : Object.keys(params).length > 0 ? (
              <span className="text-[9px] text-amber-500">({Object.keys(params).length})</span>
            ) : data.actionType ? (
              <span className="text-[8px] text-yellow-500 bg-yellow-500/10 px-1.5 py-0.5 rounded">Click to configure</span>
            ) : null}
          </div>
          {expandedSection === 'params' ? (
            <ChevronUp className="w-3 h-3 text-gray-500" />
          ) : (
            <ChevronDown className="w-3 h-3 text-gray-500" />
          )}
        </button>
        {expandedSection === 'params' && (
          <div className="px-3 pb-2 space-y-3">
            {isLoadingFields ? (
              <div className="flex items-center gap-2 py-2">
                <Loader2 className="w-3 h-3 text-amber-500 animate-spin" />
                <span className="text-[9px] text-gray-500">Loading action interface...</span>
              </div>
            ) : goalFields.length === 0 ? (
              <div className="p-2 bg-[#1a1a2e] rounded border border-gray-700">
                <p className="text-[9px] text-gray-500">
                  스키마 없음. Action Type을 선택하면 파라미터가 자동으로 표시됩니다.
                </p>
              </div>
            ) : (
              goalFields.map((field) => {
                const inputType = getInputType(field.type, field.is_array)
                const selectorInputType = inputType === 'checkbox' ? 'checkbox' : inputType === 'number' ? 'number' : 'text'
                const isSimpleType = ['checkbox', 'number', 'text'].includes(inputType)

                return (
                  <div key={field.name} className="space-y-1 p-2 bg-[#16162a] rounded border border-gray-700/50">
                    {/* Field header */}
                    <div className="flex items-center gap-2 pb-1 border-b border-gray-700/30">
                      <span className="text-[11px] text-white font-medium">{field.name}</span>
                      <span className="text-[9px] text-gray-500 font-mono px-1.5 py-0.5 bg-gray-800 rounded">
                        {field.type}{field.is_array ? '[]' : ''}
                      </span>
                    </div>

                    {/* Parameter Source Selector - integrated with value input for simple types */}
                    <ParameterSourceSelector
                      fieldSource={fieldSources[field.name]}
                      availableSteps={availableSteps}
                      onChange={(source) => updateFieldSource(field.name, source)}
                      targetFieldType={field.type}
                      targetFieldName={field.name}
                      constantValue={isSimpleType ? params[field.name] : undefined}
                      onConstantChange={isSimpleType ? (value) => updateParam(field.name, value) : undefined}
                      inputType={selectorInputType}
                    />

                    {/* Complex type inputs - shown only for constant mode with complex types */}
                    {!fieldSources[field.name]?.source && !isSimpleType && (
                      <div className="mt-1 p-2 bg-[#0d0d1a] rounded border border-amber-500/20">
                        {inputType === 'pose' && (
                          <div className="space-y-1">
                            <div className="text-[9px] text-amber-400">Position (x, y, θ)</div>
                            <div className="flex gap-1">
                              {['x', 'y', 'theta'].map((axis) => (
                                <div key={axis} className="flex-1">
                                  <label className="text-[9px] text-gray-500">{axis === 'theta' ? 'θ' : axis}</label>
                                  <input
                                    type="number"
                                    value={((params[field.name] as Record<string, number>)?.[axis]) ?? ''}
                                    onChange={(e) => {
                                      e.stopPropagation()
                                      const current = (params[field.name] as Record<string, number>) || {}
                                      updateParam(field.name, { ...current, [axis]: parseFloat(e.target.value) || 0 })
                                    }}
                                    onClick={(e) => e.stopPropagation()}
                                    className="w-full px-2 py-1 bg-[#16162a] border border-gray-700 rounded text-[11px] text-white focus:outline-none focus:border-amber-500"
                                    placeholder="0"
                                    step="0.01"
                                  />
                                </div>
                              ))}
                            </div>
                          </div>
                        )}
                        {inputType === 'complex' && (
                          <div className="space-y-1">
                            <div className="text-[9px] text-amber-400">JSON 입력</div>
                            <textarea
                              value={typeof params[field.name] === 'object'
                                ? JSON.stringify(params[field.name], null, 2)
                                : (params[field.name] as string) || ''}
                              onChange={(e) => {
                                e.stopPropagation()
                                try {
                                  const parsed = JSON.parse(e.target.value)
                                  updateParam(field.name, parsed)
                                } catch {
                                  updateParam(field.name, e.target.value)
                                }
                              }}
                              onClick={(e) => e.stopPropagation()}
                              className="w-full px-2 py-1 bg-[#16162a] border border-gray-700 rounded text-[10px] text-gray-300 font-mono focus:outline-none resize-none"
                              placeholder="{}"
                              rows={3}
                            />
                          </div>
                        )}
                        {inputType === 'trajectory' && (
                          <div className="text-[9px] text-gray-500">
                            Trajectory는 이전 Step의 결과를 바인딩하세요
                          </div>
                        )}
                      </div>
                    )}
                  </div>
                )
              })
            )}
          </div>
        )}
        </div>

      {/* Result Schema Section - Output fields from ROS2 Action (read-only, for reference) */}
      <div className="border-b border-[#2a2a4a]">
        <button
          onClick={(e) => { e.stopPropagation(); setExpandedSection(expandedSection === 'result' ? null : 'result') }}
          className="w-full px-3 py-1.5 flex items-center justify-between hover:bg-[#2a2a4a]/50 transition-colors"
        >
          <div className="flex items-center gap-2">
            <Download className="w-3 h-3 text-green-500" />
            <span className="text-[10px] text-green-400 uppercase tracking-wider font-medium">Result Schema</span>
            <span className="text-[8px] text-gray-600 italic">← Receive</span>
            {isLoadingFields ? (
              <Loader2 className="w-3 h-3 text-green-500 animate-spin" />
            ) : resultFields.length > 0 ? (
              <span className="text-[9px] text-gray-600">({resultFields.length})</span>
            ) : (
              <span className="text-[8px] text-gray-600">-</span>
            )}
          </div>
          {expandedSection === 'result' ? (
            <ChevronUp className="w-3 h-3 text-gray-500" />
          ) : (
            <ChevronDown className="w-3 h-3 text-gray-500" />
          )}
        </button>
        {expandedSection === 'result' && (
          <div className="px-3 pb-2 space-y-2">
            {isLoadingFields ? (
              <div className="flex items-center gap-2 py-2">
                <Loader2 className="w-3 h-3 text-green-500 animate-spin" />
                <span className="text-[9px] text-gray-500">Loading result schema...</span>
              </div>
            ) : resultFields.length === 0 ? (
              <div className="p-2 bg-[#1a1a2e] rounded border border-gray-700">
                <p className="text-[9px] text-gray-500">No result schema available from capability API</p>
              </div>
            ) : (
              <>
                <div className="p-2 bg-green-900/20 rounded border border-green-500/30">
                  <p className="text-[9px] text-green-400 mb-1.5">
                    These fields are available after this step completes successfully.
                  </p>
                  <p className="text-[8px] text-gray-500">
                    Use <code className="text-purple-400">${'{'}step_id.field{'}'}</code> to bind to other steps.
                  </p>
                </div>
                <div className="space-y-1">
                  {resultFields.map((field) => (
                    <div
                      key={field.name}
                      className="flex items-center justify-between px-2 py-1.5 bg-[#16162a] rounded border border-green-500/20"
                    >
                      <div className="flex items-center gap-2">
                        <span className="text-[9px] text-green-400 font-mono">{field.name}</span>
                      </div>
                      <div className="flex items-center gap-2">
                        <span className="text-[8px] text-gray-600 font-mono px-1.5 py-0.5 bg-gray-800 rounded">
                          {field.type}{field.is_array ? '[]' : ''}
                        </span>
                        <code className="text-[8px] text-purple-400 bg-purple-500/10 px-1.5 py-0.5 rounded">
                          ${'{'}${jobName || id}.{field.name}{'}'}
                        </code>
                      </div>
                    </div>
                  ))}
                </div>
              </>
            )}
          </div>
        )}
      </div>

      {/* Start Conditions Section */}
      <div className="border-b border-[#2a2a4a]">
        <button
          onClick={(e) => { e.stopPropagation(); setExpandedSection(expandedSection === 'start' ? null : 'start') }}
          className="w-full px-3 py-1.5 flex items-center justify-between hover:bg-[#2a2a4a]/50 transition-colors"
        >
          <div className="flex items-center gap-2">
            <div className="w-2 h-2 rounded-full bg-cyan-500" />
            <span className="text-[10px] text-cyan-400 uppercase tracking-wider font-medium">Start Conditions</span>
            <span className="text-[9px] text-gray-600">({startStates.length})</span>
          </div>
          {expandedSection === 'start' ? (
            <ChevronUp className="w-3 h-3 text-gray-500" />
          ) : (
            <ChevronDown className="w-3 h-3 text-gray-500" />
          )}
        </button>
        {expandedSection === 'start' && (
          <div className="px-3 pb-2 space-y-1.5">
            <p className="text-[9px] text-gray-500">
              Preconditions before this step starts. Every=all robots in scope, Any=at least one.
            </p>
            {startStates.length === 0 ? (
              <p className="text-[9px] text-gray-600 italic">No preconditions</p>
            ) : (
              startStates.map((ss, idx) => (
                <div key={ss.id} className="flex flex-wrap items-center gap-1 text-[9px] bg-cyan-500/10 px-2 py-1.5 rounded group min-w-0 overflow-hidden">
                  {/* Operator (and/or) - only for 2nd+ conditions */}
                  {idx > 0 && (
                    <select
                      value={ss.operator || 'and'}
                      onChange={(e) => {
                        e.stopPropagation()
                        updateStartStateField(ss.id, 'operator', e.target.value as 'and' | 'or')
                      }}
                      onClick={(e) => e.stopPropagation()}
                      className="bg-[#16162a] text-[9px] text-orange-400 font-bold uppercase focus:outline-none cursor-pointer rounded px-1.5 py-0.5 border border-orange-500/30 flex-shrink-0"
                    >
                      <option value="and" className="bg-[#1a1a2e]">AND</option>
                      <option value="or" className="bg-[#1a1a2e]">OR</option>
                    </select>
                  )}

                  {/* Quantifier (Self/Every/Any/Specific) */}
                  <select
                    value={ss.quantifier || 'self'}
                    onChange={(e) => {
                      e.stopPropagation()
                      updateStartStateField(ss.id, 'quantifier', e.target.value as 'self' | 'every' | 'any' | 'specific')
                    }}
                    onClick={(e) => e.stopPropagation()}
                    className="bg-[#16162a] text-[9px] text-purple-400 font-medium focus:outline-none cursor-pointer rounded px-1.5 py-0.5 border border-purple-500/30 flex-shrink-0"
                  >
                    <option value="self" className="bg-[#1a1a2e]">Self</option>
                    <option value="every" className="bg-[#1a1a2e]">Every</option>
                    <option value="any" className="bg-[#1a1a2e]">Any</option>
                    <option value="specific" className="bg-[#1a1a2e]">Agent</option>
                  </select>

                  {/* Agent (only for every/any) */}
                  {(ss.quantifier === 'every' || ss.quantifier === 'any') && (
                    <select
                      value={ss.agentId || availableAgents[0]?.id || ''}
                      onChange={(e) => {
                        e.stopPropagation()
                        updateStartStateField(ss.id, 'agentId', e.target.value)
                      }}
                      onClick={(e) => e.stopPropagation()}
                      className="bg-[#16162a] text-[9px] text-blue-400 focus:outline-none cursor-pointer rounded px-1.5 py-0.5 border border-blue-500/30 max-w-[80px] truncate"
                    >
                      {availableAgents.length > 0 ? (
                        availableAgents.map(agent => (
                          <option key={agent.id} value={agent.id} className="bg-[#1a1a2e]">
                            {agent.name}
                          </option>
                        ))
                      ) : (
                        <option value="" className="bg-[#1a1a2e]">No agents</option>
                      )}
                    </select>
                  )}

                  {/* Specific Agent (only for specific) */}
                  {ss.quantifier === 'specific' && (
                    <div className="min-w-0 max-w-[80px]">
                      <input
                        type="text"
                        list={`start-agent-options-${ss.id}`}
                        value={(() => {
                          if (ss.agentId) {
                            const match = availableAgents.find(agent => agent.id === ss.agentId)
                            return match ? match.name : ss.agentId
                          }
                          return ''
                        })()}
                        onChange={(e) => {
                          e.stopPropagation()
                          const value = e.target.value
                          const matchById = availableAgents.find(agent => agent.id === value)
                          if (matchById) {
                            updateStartStateField(ss.id, 'agentId', matchById.id)
                            return
                          }
                          const matchByName = availableAgents.find(agent => agent.name === value)
                          if (matchByName) {
                            updateStartStateField(ss.id, 'agentId', matchByName.id)
                            return
                          }
                          updateStartStateField(ss.id, 'agentId', value)
                        }}
                        onClick={(e) => e.stopPropagation()}
                        placeholder="Agent"
                        className="w-full bg-[#16162a] text-[9px] text-green-400 focus:outline-none cursor-pointer rounded px-1.5 py-0.5 border border-green-500/30 truncate"
                        title={ss.agentId || 'Select or enter agent'}
                      />
                      <datalist id={`start-agent-options-${ss.id}`}>
                        {availableAgents.map(agent => (
                          <option key={agent.id} value={agent.name} />
                        ))}
                      </datalist>
                    </div>
                  )}

                  <span className="text-gray-500 flex-shrink-0">is</span>

                  {/* State */}
                  <select
                    value={ss.state}
                    onChange={(e) => {
                      e.stopPropagation()
                      updateStartStateField(ss.id, 'state', e.target.value)
                    }}
                    onClick={(e) => e.stopPropagation()}
                    className="bg-[#16162a] text-[9px] text-cyan-400 font-mono focus:outline-none cursor-pointer rounded px-1.5 py-0.5 border border-cyan-500/30 max-w-[70px] truncate"
                    title={ss.state}
                  >
                    {states.map(s => <option key={s} value={s} className="bg-[#1a1a2e]">{s}</option>)}
                  </select>

                  {/* Delete button */}
                  <button
                    onClick={(e) => {
                      e.stopPropagation()
                      removeStartState(ss.id)
                    }}
                    className="ml-auto opacity-0 group-hover:opacity-100 transition-opacity"
                  >
                    <X className="w-2.5 h-2.5 text-cyan-500/70 hover:text-red-400" />
                  </button>
                </div>
              ))
            )}
            <button
              onClick={(e) => { e.stopPropagation(); addStartState() }}
              className="text-[9px] text-cyan-400 hover:text-cyan-300"
            >
              + Add start condition
            </button>
          </div>
        )}
      </div>

      {/* During States Section */}
      <div className="px-3 py-2 border-b border-[#2a2a4a]">
        <div className="flex items-center justify-between mb-1.5">
          <div className="flex items-center gap-2">
            <div className="w-2 h-2 rounded-full bg-yellow-500 animate-pulse" />
            <span className="text-[10px] text-yellow-400 uppercase tracking-wider font-medium">During States</span>
          </div>
          <button
            onClick={(e) => { e.stopPropagation(); addDuringState() }}
            className="p-0.5 hover:bg-yellow-500/20 rounded transition-colors"
          >
            <Plus className="w-2.5 h-2.5 text-yellow-500" />
          </button>
        </div>
        <p className="text-[9px] text-gray-500 mb-1">
          Temporary override while executing; non-self targets revert on completion.
        </p>
        <div className="flex flex-wrap gap-1">
          {duringStateTargets.length === 0 ? (
            <span className="text-[9px] text-gray-600 italic">No states during execution</span>
          ) : (
            duringStateTargets.map((target, i) => (
              <div key={i} className="flex items-center gap-1 px-2 py-0.5 bg-yellow-500/10 border border-yellow-500/30 rounded-full group">
                <select
                  value={target.state}
                  onChange={(e) => {
                    e.stopPropagation()
                    const next = [...duringStateTargets]
                    next[i] = { ...next[i], state: e.target.value }
                    updateData('duringStateTargets', next)
                  }}
                  onClick={(e) => e.stopPropagation()}
                  className="bg-[#1a1a2e] text-[9px] text-yellow-400 font-medium focus:outline-none cursor-pointer rounded px-1"
                >
                  {states.map(s => <option key={s} value={s} className="bg-[#1a1a2e]">{s}</option>)}
                </select>
                <select
                  value={target.target_type || 'self'}
                  onChange={(e) => {
                    e.stopPropagation()
                    const next = [...duringStateTargets]
                    const nextTarget: NormalizedDuringStateTarget = {
                      ...next[i],
                      target_type: e.target.value as NormalizedDuringStateTarget['target_type'],
                    }
                    if (nextTarget.target_type !== 'agent') {
                      nextTarget.agent_id = undefined
                    } else if (!nextTarget.agent_id && availableAgents.length > 0) {
                      nextTarget.agent_id = availableAgents[0].id
                    }
                    next[i] = nextTarget
                    updateData('duringStateTargets', next)
                  }}
                  onClick={(e) => e.stopPropagation()}
                  className="bg-[#1a1a2e] text-[9px] text-yellow-300 font-medium focus:outline-none cursor-pointer rounded px-1"
                >
                  {DURING_TARGET_OPTIONS.map(option => (
                    <option key={option.value} value={option.value} className="bg-[#1a1a2e]">
                      {option.label}
                    </option>
                  ))}
                </select>
                {target.target_type === 'agent' && (
                  <select
                    value={target.agent_id || ''}
                    onChange={(e) => {
                      e.stopPropagation()
                      const next = [...duringStateTargets]
                      next[i] = { ...next[i], agent_id: e.target.value }
                      updateData('duringStateTargets', next)
                    }}
                    onClick={(e) => e.stopPropagation()}
                    className="bg-[#1a1a2e] text-[9px] text-yellow-300 font-medium focus:outline-none cursor-pointer rounded px-1"
                  >
                    {availableAgents.length === 0 && (
                      <option value="" className="bg-[#1a1a2e]">No agents</option>
                    )}
                    {availableAgents.map(agent => (
                      <option key={agent.id} value={agent.id} className="bg-[#1a1a2e]">
                        {agent.name}
                      </option>
                    ))}
                  </select>
                )}
                <button
                  onClick={(e) => {
                    e.stopPropagation()
                    updateData('duringStateTargets', duringStateTargets.filter((_, idx) => idx !== i))
                  }}
                  className="opacity-0 group-hover:opacity-100 transition-opacity"
                >
                  <X className="w-2.5 h-2.5 text-yellow-500/70 hover:text-yellow-500" />
                </button>
              </div>
            ))
          )}
        </div>
      </div>

      {/* End States Section */}
      <div className="px-3 py-2">
        <div className="flex items-center justify-between mb-1.5">
          <div className="flex items-center gap-2">
            <div className="w-2 h-2 rounded-sm bg-gradient-to-r from-green-500 to-red-500" />
            <span className="text-[10px] text-gray-300 uppercase tracking-wider font-medium">End States</span>
          </div>
          <button
            onClick={(e) => { e.stopPropagation(); addEndState() }}
            className="p-0.5 hover:bg-gray-500/20 rounded transition-colors"
          >
            <Plus className="w-2.5 h-2.5 text-gray-400" />
          </button>
        </div>
        <p className="text-[9px] text-gray-500 mb-1">
          Final state per outcome. ROS2: SUCCEEDED/ABORTED/CANCELED.
        </p>
        <div className="space-y-1">
          {endStates.map((endState) => (
            <div
              key={endState.id}
              className="flex items-center gap-2"
            >
              <div
                className="w-2 h-2 rounded-full flex-shrink-0"
                style={{ backgroundColor: endState.color || getEndStateColor(endState) }}
              />
              <select
                value={endState.outcome || inferOutcomeFromEndState(endState)}
                onChange={(e) => {
                  e.stopPropagation()
                  updateEndState(endState.id, 'outcome', e.target.value)
                }}
                onClick={(e) => e.stopPropagation()}
                className="w-20 px-1 py-0.5 bg-[#16162a] border border-gray-700 rounded text-[9px] text-gray-300 focus:outline-none cursor-pointer"
              >
                {OUTCOME_OPTIONS.map(option => (
                  <option key={option.value} value={option.value} className="bg-[#16162a]">
                    {option.label}
                  </option>
                ))}
              </select>
              <input
                type="text"
                value={endState.label || ''}
                onChange={(e) => {
                  e.stopPropagation()
                  updateEndState(endState.id, 'label', e.target.value)
                }}
                onClick={(e) => e.stopPropagation()}
                placeholder="Label"
                className="w-16 px-1 py-0.5 bg-transparent border-b border-gray-700 text-[9px] text-gray-300 focus:outline-none focus:border-gray-500"
              />
              <span className="text-[9px] text-gray-600">→</span>
              <select
                value={endState.state}
                onChange={(e) => {
                  e.stopPropagation()
                  updateEndState(endState.id, 'state', e.target.value)
                }}
                onClick={(e) => e.stopPropagation()}
                className="flex-1 px-1 py-0.5 bg-[#16162a] border border-gray-700 rounded text-[9px] focus:outline-none cursor-pointer"
                style={{ color: endState.color || getEndStateColor(endState) }}
              >
                {states.map(s => <option key={s} value={s} className="bg-[#16162a]">{s}</option>)}
              </select>
              {endStates.length > 1 && (
                <button
                  onClick={(e) => { e.stopPropagation(); removeEndState(endState.id) }}
                  className="text-gray-600 hover:text-red-400 transition-colors"
                >
                  <X className="w-2.5 h-2.5" />
                </button>
              )}
            </div>
          ))}
        </div>
      </div>

      {/* Footer */}
	      <div
	        className="px-3 py-1 border-t border-[#2a2a4a] flex items-center justify-between"
	        style={{ backgroundColor: '#16162a' }}
	      >
	        <span className="text-[9px] text-gray-500 font-mono truncate max-w-[180px]">
	          {data.server || data.subtype}
	        </span>
	        <div className="w-1.5 h-1.5 rounded-full bg-green-500" />
	      </div>

	      {/* Handles (render last to avoid being covered by overflowing content) */}
	      <Handle
	        type="target"
	        position={Position.Left}
	        id="in"
	        className="!w-4 !h-4 !bg-cyan-500 !border-2 !border-cyan-300 !rounded-full hover:!w-5 hover:!h-5 hover:!bg-cyan-400 transition-all cursor-crosshair !pointer-events-auto"
	        style={{ position: 'absolute', left: -8, top: '18%', zIndex: 1000, pointerEvents: 'auto' }}
	        title="Input (from previous action)"
	      />
	      <Handle
	        type="source"
	        position={Position.Right}
	        id="success"
	        className="!w-4 !h-4 !border-2 !rounded-full hover:!w-5 hover:!h-5 transition-all cursor-crosshair !pointer-events-auto"
	        style={{ position: 'absolute', right: -8, top: '70%', backgroundColor: '#22c55e', borderColor: '#22c55e99', zIndex: 1000, pointerEvents: 'auto' }}
	        title="Success: Drag to connect"
	      />
	      <Handle
	        type="source"
	        position={Position.Right}
	        id="failed"
	        className="!w-4 !h-4 !border-2 !rounded-full hover:!w-5 hover:!h-5 transition-all cursor-crosshair !pointer-events-auto"
	        style={{ position: 'absolute', right: -8, top: '77%', backgroundColor: '#ef4444', borderColor: '#ef444499', zIndex: 1000, pointerEvents: 'auto' }}
	        title="Failed: Drag to connect"
	      />
	      <Handle
	        type="source"
	        position={Position.Right}
	        id="aborted"
	        className="!w-4 !h-4 !border-2 !rounded-full hover:!w-5 hover:!h-5 transition-all cursor-crosshair !pointer-events-auto"
	        style={{ position: 'absolute', right: -8, top: '84%', backgroundColor: '#ef4444', borderColor: '#ef444499', zIndex: 1000, pointerEvents: 'auto' }}
	        title="Aborted: Drag to connect"
	      />
	      <Handle
	        type="source"
	        position={Position.Right}
	        id="cancelled"
	        className="!w-4 !h-4 !border-2 !rounded-full hover:!w-5 hover:!h-5 transition-all cursor-crosshair !pointer-events-auto"
	        style={{ position: 'absolute', right: -8, top: '91%', backgroundColor: '#6b7280', borderColor: '#6b728099', zIndex: 1000, pointerEvents: 'auto' }}
	        title="Cancelled: Drag to connect"
	      />
	    </div>
	  )
	})

StateActionNode.displayName = 'StateActionNode'

export default StateActionNode
