import type { ActionField, EndStateConfig, ActionOutcome, GraphState } from '../../../types'
import type { InputType } from './types'
import { AUTO_STATE_SUFFIXES, OUTCOME_COLORS, END_STATE_COLORS } from './constants'

// Generate states from node name
export const generateStatesFromNodeName = (nodeName: string): {
  during: string
  succeed: string
  failed: string
  aborted: string
  cancelled: string
  timeout: string
} => {
  const sanitized = nodeName.toLowerCase().replace(/\s+/g, '_').replace(/[^a-z0-9_]/g, '')
  return {
    during: `${sanitized}${AUTO_STATE_SUFFIXES.during}`,
    succeed: `${sanitized}${AUTO_STATE_SUFFIXES.succeed}`,
    failed: `${sanitized}${AUTO_STATE_SUFFIXES.failed}`,
    aborted: `${sanitized}${AUTO_STATE_SUFFIXES.aborted}`,
    cancelled: `${sanitized}${AUTO_STATE_SUFFIXES.cancelled}`,
    timeout: `${sanitized}${AUTO_STATE_SUFFIXES.timeout}`,
  }
}

// Create GraphState objects from auto-generated states
export const createAutoGeneratedGraphStates = (nodeName: string, stepId: string): GraphState[] => {
  const states = generateStatesFromNodeName(nodeName)
  return [
    { code: states.during, name: `${nodeName} (During)`, type: 'graph', step_id: stepId, phase: 'executing', color: '#EAB308', semantic_tags: ['executing', 'busy', nodeName.toLowerCase()] },
    { code: states.succeed, name: `${nodeName} (Success)`, type: 'graph', step_id: stepId, phase: 'success', color: '#22C55E', semantic_tags: ['success', 'completed', nodeName.toLowerCase()] },
    { code: states.failed, name: `${nodeName} (Failed)`, type: 'graph', step_id: stepId, phase: 'failed', color: '#EF4444', semantic_tags: ['failed', 'error', nodeName.toLowerCase()] },
    { code: states.aborted, name: `${nodeName} (Aborted)`, type: 'graph', step_id: stepId, phase: 'failed', color: '#EF4444', semantic_tags: ['aborted', 'error', nodeName.toLowerCase()] },
    { code: states.cancelled, name: `${nodeName} (Cancelled)`, type: 'graph', step_id: stepId, phase: 'failed', color: '#6B7280', semantic_tags: ['cancelled', nodeName.toLowerCase()] },
    { code: states.timeout, name: `${nodeName} (Timeout)`, type: 'graph', step_id: stepId, phase: 'failed', color: '#F59E0B', semantic_tags: ['timeout', 'error', nodeName.toLowerCase()] },
  ]
}

// Helper to extract ROS2 type from JSON Schema field info
const extractRosType = (info: Record<string, unknown>): { type: string; isArray: boolean } => {
  // Check for array type first
  if (info.type === 'array' && info.items && typeof info.items === 'object') {
    const items = info.items as Record<string, unknown>
    const itemType = extractRosType(items)
    return { type: itemType.type, isArray: true }
  }

  // Check for x-ros-namespace and x-ros-name (from C++ schema extractor)
  const rosNamespace = info['x-ros-namespace'] as string | undefined
  const rosName = info['x-ros-name'] as string | undefined

  if (rosNamespace && rosName) {
    // Normalize namespace separators from C++ extractor:
    // "geometry_msgs::msg" or "geometry_msgs__msg" -> "geometry_msgs/msg"
    const namespace = rosNamespace
      .replace(/::/g, '/')
      .replace(/__/g, '/')
      .replace(/\/+/g, '/')
    return { type: `${namespace}/${rosName}`, isArray: false }
  }

  // Check for x-ros-type (simplified type name)
  const xRosType = info['x-ros-type'] as string | undefined
  if (xRosType && xRosType !== 'message' && xRosType !== 'object') {
    return { type: xRosType, isArray: false }
  }

  // Fall back to JSON Schema type
  const jsonType = info.type as string | undefined
  return { type: jsonType || 'string', isArray: false }
}

// Convert capability goal_schema to ActionField format
export const schemaToFields = (schema: Record<string, unknown> | null): ActionField[] => {
  if (!schema) return []

  const fields: ActionField[] = []

  // Check if this is a JSON Schema format
  if (schema.type === 'object' && schema.properties && typeof schema.properties === 'object') {
    const properties = schema.properties as Record<string, unknown>
    for (const [name, fieldInfo] of Object.entries(properties)) {
      if (typeof fieldInfo === 'object' && fieldInfo !== null) {
        const info = fieldInfo as Record<string, unknown>
        const { type, isArray } = extractRosType(info)

        fields.push({
          name,
          type,
          default: info.default as string | undefined,
          is_array: isArray || Boolean(info.is_array),
          is_constant: false,
        })
      } else if (typeof fieldInfo === 'string') {
        fields.push({
          name,
          type: fieldInfo,
          is_array: false,
          is_constant: false,
        })
      }
    }
    return fields
  }

  // Legacy/simple ROS2 message schema format
  const metadataFields = ['type', 'properties', 'x-ros-name', 'x-ros-namespace', 'required', 'additionalProperties']

  for (const [name, fieldInfo] of Object.entries(schema)) {
    if (metadataFields.includes(name)) continue

    if (typeof fieldInfo === 'object' && fieldInfo !== null) {
      const info = fieldInfo as Record<string, unknown>
      const { type, isArray } = extractRosType(info)

      fields.push({
        name,
        type,
        default: info.default as string | undefined,
        is_array: isArray || Boolean(info.is_array),
        is_constant: false,
      })
    } else if (typeof fieldInfo === 'string') {
      fields.push({
        name,
        type: fieldInfo,
        is_array: false,
        is_constant: false,
      })
    }
  }

  return fields
}

// Map ROS2 types to input types
export const getInputType = (rosType: string, isArray: boolean): InputType => {
  const numericTypes = ['int8', 'int16', 'int32', 'int64', 'uint8', 'uint16', 'uint32', 'uint64', 'float32', 'float64', 'double']

  if (rosType.includes('/')) {
    const lowerType = rosType.toLowerCase()
    if (lowerType.includes('pose') || lowerType.includes('point') || lowerType.includes('transform')) {
      return 'pose'
    }
    if (lowerType.includes('trajectory') || lowerType.includes('jointtrajectory')) {
      return 'trajectory'
    }
    return 'complex'
  }

  if (rosType === 'bool') return 'checkbox'
  if (numericTypes.some(t => rosType === t)) return 'number'
  if (rosType === 'string') return 'text'
  if (isArray) return 'complex'

  return 'text'
}

export const normalizeOutcomeValue = (value?: string): ActionOutcome | undefined => {
  if (!value) return undefined
  const lower = value.toLowerCase()
  if (lower === 'success' || lower === 'succeeded') return 'success'
  if (lower === 'failed' || lower === 'failure' || lower === 'error') return 'failed'
  if (lower === 'aborted' || lower === 'abort') return 'aborted'
  if (lower === 'cancelled' || lower === 'canceled' || lower === 'cancel') return 'cancelled'
  if (lower === 'timeout' || lower === 'timed_out') return 'timeout'
  if (lower === 'rejected') return 'rejected'
  return undefined
}

export const inferOutcomeFromEndState = (endState: EndStateConfig): ActionOutcome => {
  const label = (endState.label || '').toLowerCase()
  const stateValue = (endState.state || '').toLowerCase()

  if (label.includes('timeout') || stateValue.includes('timeout')) return 'timeout'
  if (label.includes('cancel') || stateValue.includes('cancel')) return 'cancelled'
  if (label.includes('abort') || stateValue.includes('abort')) return 'aborted'
  if (label.includes('fail') || label.includes('error') || stateValue.includes('fail') || stateValue.includes('error')) return 'failed'
  if (label.includes('success') || label.includes('complete') || stateValue.includes('idle') || stateValue.includes('ready')) return 'success'
  return 'success'
}

export const getEndStateColor = (endState: EndStateConfig): string => {
  if (endState.color) return endState.color
  if (endState.outcome && OUTCOME_COLORS[endState.outcome]) return OUTCOME_COLORS[endState.outcome]
  if (endState.label) {
    const lowerLabel = endState.label.toLowerCase()
    if (lowerLabel.includes('success') || lowerLabel.includes('complete')) return '#22c55e'
    if (lowerLabel.includes('error') || lowerLabel.includes('fail') || lowerLabel.includes('abort')) return '#ef4444'
    if (lowerLabel.includes('timeout')) return '#f59e0b'
  }
  return END_STATE_COLORS[endState.state.toLowerCase()] || '#6b7280'
}

// Check if a field type is a numeric array type
export const isNumericArrayType = (type: string): boolean => {
  const lowerType = type.toLowerCase()
  return (
    lowerType.includes('float64[]') ||
    lowerType.includes('double[]') ||
    lowerType.includes('float32[]') ||
    lowerType.includes('sequence<double>') ||
    lowerType.includes('sequence<float64>') ||
    lowerType.includes('sequence<float32>') ||
    (lowerType.includes('float') && lowerType.includes('[]')) ||
    (lowerType.includes('double') && lowerType.includes('[]'))
  )
}

// Check if a field type is a string array type
export const isStringArrayType = (type: string): boolean => {
  const lowerType = type.toLowerCase()
  return (
    lowerType.includes('string[]') ||
    lowerType.includes('sequence<string>')
  )
}
