import React, { useState, useMemo } from 'react'
import {
  Activity, Tag, Plus, Trash2, ChevronDown, ChevronRight,
  Settings2, Edit2, Check, X, Circle
} from 'lucide-react'
import type { GraphState, StatePhase } from '../types'

// System states are predefined and always available
export const SystemStates: GraphState[] = [
  { code: 'idle', name: 'Idle', type: 'system', phase: 'idle', color: '#6B7280', description: 'Agent is idle and ready', semantic_tags: ['ready', 'available'] },
  { code: 'executing', name: 'Executing', type: 'system', phase: 'executing', color: '#3B82F6', description: 'Agent is executing an action', semantic_tags: ['busy', 'working'] },
  { code: 'error', name: 'Error', type: 'system', phase: 'failed', color: '#EF4444', description: 'Agent encountered an error', semantic_tags: ['error', 'fault'] },
  { code: 'offline', name: 'Offline', type: 'system', phase: 'idle', color: '#9CA3AF', description: 'Agent is offline', semantic_tags: ['unavailable'] },
]

// Phase colors for auto-generated states
const PHASE_COLORS: Record<StatePhase, string> = {
  idle: '#6B7280',
  executing: '#3B82F6',
  success: '#22C55E',
  failed: '#EF4444',
}

interface StatesPanelProps {
  // Graph states (custom + auto-generated)
  states: GraphState[]
  onChange: (states: GraphState[]) => void

  // Auto-generation toggle
  autoGenerateStates: boolean
  onAutoGenerateChange: (enabled: boolean) => void

  // Step IDs for auto-generation
  stepIds: string[]

  // Compact mode for smaller display
  compact?: boolean
}

export default function StatesPanel({
  states,
  onChange,
  autoGenerateStates,
  onAutoGenerateChange,
  stepIds,
  compact = false,
}: StatesPanelProps) {
  const [expandedSections, setExpandedSections] = useState<string[]>(['system', 'graph', 'custom'])
  const [showAddCustom, setShowAddCustom] = useState(false)
  const [editingState, setEditingState] = useState<string | null>(null)

  // Separate states by type
  const { graphStates, customStates } = useMemo(() => {
    const graph: GraphState[] = []
    const custom: GraphState[] = []

    states.forEach(state => {
      if (state.type === 'graph') {
        graph.push(state)
      } else if (state.type === 'custom') {
        custom.push(state)
      }
    })

    return { graphStates: graph, customStates: custom }
  }, [states])

  // Auto-generate states from step IDs
  const autoGeneratedStates = useMemo((): GraphState[] => {
    if (!autoGenerateStates) return []

    const generated: GraphState[] = []
    const phases: StatePhase[] = ['executing', 'success', 'failed']

    stepIds.forEach(stepId => {
      phases.forEach(phase => {
        const code = `${stepId}:${phase}`
        // Only add if not already in custom states
        const existsInCustom = customStates.some(s => s.code === code)
        if (!existsInCustom) {
          generated.push({
            code,
            name: `${stepId} (${phase})`,
            type: 'graph',
            step_id: stepId,
            phase,
            color: PHASE_COLORS[phase],
            description: `Step ${stepId} ${phase} state`,
            semantic_tags: [phase, stepId],
          })
        }
      })
    })

    return generated
  }, [autoGenerateStates, stepIds, customStates])

  // All states combined (including auto-generated)
  const allGraphStates = useMemo(() => {
    // Merge auto-generated with explicitly saved graph states
    const savedGraphIds = new Set(graphStates.map(s => s.code))
    const autoGen = autoGeneratedStates.filter(s => !savedGraphIds.has(s.code))
    return [...graphStates, ...autoGen]
  }, [graphStates, autoGeneratedStates])

  const toggleSection = (section: string) => {
    setExpandedSections(prev =>
      prev.includes(section)
        ? prev.filter(s => s !== section)
        : [...prev, section]
    )
  }

  const addCustomState = (state: GraphState) => {
    onChange([...states, { ...state, type: 'custom' }])
    setShowAddCustom(false)
  }

  const updateState = (code: string, updates: Partial<GraphState>) => {
    onChange(states.map(s => s.code === code ? { ...s, ...updates } : s))
  }

  const deleteState = (code: string) => {
    onChange(states.filter(s => s.code !== code))
  }

  const sectionClasses = compact ? 'px-2 py-1.5' : 'px-3 py-2'
  const headerClasses = compact ? 'text-[10px]' : 'text-xs'

  return (
    <div className="space-y-1">
      {/* Auto-generate Toggle */}
      <div className={`${sectionClasses} border-b border-[#2a2a4a]`}>
        <label className="flex items-center gap-2 cursor-pointer group">
          <input
            type="checkbox"
            checked={autoGenerateStates}
            onChange={(e) => onAutoGenerateChange(e.target.checked)}
            className="w-4 h-4 rounded border-gray-500 bg-[#1a1a2e] text-blue-500 focus:ring-blue-500 focus:ring-offset-0"
          />
          <span className={`${headerClasses} text-gray-400 group-hover:text-gray-300`}>
            Auto-generate states from steps
          </span>
          <Settings2 className="w-3 h-3 text-gray-600 group-hover:text-gray-500" />
        </label>
        {autoGenerateStates && (
          <p className="text-[9px] text-gray-600 mt-1 ml-6">
            Creates {stepIds.length * 3} states ({stepIds.length} steps × 3 phases)
          </p>
        )}
      </div>

      {/* System States Section */}
      <StateSection
        title="System States"
        icon={<Activity className="w-3 h-3" />}
        states={SystemStates}
        expanded={expandedSections.includes('system')}
        onToggle={() => toggleSection('system')}
        compact={compact}
        readonly
      />

      {/* Graph States Section (Auto-generated) */}
      {allGraphStates.length > 0 && (
        <StateSection
          title="Graph States"
          icon={<Circle className="w-3 h-3" />}
          states={allGraphStates}
          expanded={expandedSections.includes('graph')}
          onToggle={() => toggleSection('graph')}
          compact={compact}
          onEdit={(code) => setEditingState(code)}
          editingCode={editingState}
          onSaveEdit={(code, updates) => {
            updateState(code, updates)
            setEditingState(null)
          }}
          onCancelEdit={() => setEditingState(null)}
          badge={autoGenerateStates ? 'auto' : undefined}
        />
      )}

      {/* Custom States Section */}
      <StateSection
        title="Custom States"
        icon={<Tag className="w-3 h-3" />}
        states={customStates}
        expanded={expandedSections.includes('custom')}
        onToggle={() => toggleSection('custom')}
        compact={compact}
        onEdit={(code) => setEditingState(code)}
        onDelete={deleteState}
        editingCode={editingState}
        onSaveEdit={(code, updates) => {
          updateState(code, updates)
          setEditingState(null)
        }}
        onCancelEdit={() => setEditingState(null)}
      />

      {/* Add Custom State Button */}
      <div className={sectionClasses}>
        {showAddCustom ? (
          <AddStateForm
            onAdd={addCustomState}
            onCancel={() => setShowAddCustom(false)}
            existingCodes={[...SystemStates, ...states].map(s => s.code)}
          />
        ) : (
          <button
            onClick={() => setShowAddCustom(true)}
            className="w-full flex items-center justify-center gap-1.5 py-1.5 text-xs text-blue-400 bg-blue-500/10 hover:bg-blue-500/20 border border-blue-500/20 rounded transition-colors"
          >
            <Plus className="w-3 h-3" />
            Add Custom State
          </button>
        )}
      </div>
    </div>
  )
}

interface StateSectionProps {
  title: string
  icon: React.ReactNode
  states: GraphState[]
  expanded: boolean
  onToggle: () => void
  compact?: boolean
  readonly?: boolean
  onEdit?: (code: string) => void
  onDelete?: (code: string) => void
  editingCode?: string | null
  onSaveEdit?: (code: string, updates: Partial<GraphState>) => void
  onCancelEdit?: () => void
  badge?: string
}

function StateSection({
  title,
  icon,
  states,
  expanded,
  onToggle,
  compact = false,
  readonly = false,
  onEdit,
  onDelete,
  editingCode,
  onSaveEdit,
  onCancelEdit,
  badge,
}: StateSectionProps) {
  if (states.length === 0 && readonly) return null

  const headerClasses = compact ? 'px-2 py-1' : 'px-3 py-1.5'

  return (
    <div>
      <button
        onClick={onToggle}
        className={`w-full ${headerClasses} flex items-center justify-between text-[10px] font-semibold text-gray-400 uppercase tracking-wider hover:bg-[#1a1a2e] transition-colors`}
      >
        <div className="flex items-center gap-1.5">
          {icon}
          <span>{title}</span>
          <span className="text-gray-600 normal-case font-normal">({states.length})</span>
          {badge && (
            <span className="px-1.5 py-0.5 text-[8px] bg-blue-500/20 text-blue-400 rounded font-normal normal-case">
              {badge}
            </span>
          )}
        </div>
        {expanded ? (
          <ChevronDown className="w-3 h-3" />
        ) : (
          <ChevronRight className="w-3 h-3" />
        )}
      </button>

      {expanded && (
        <div className={compact ? 'px-1 pb-1' : 'px-2 pb-2'}>
          {states.length === 0 ? (
            <div className="px-2 py-2 text-[10px] text-gray-600 text-center">
              No custom states defined
            </div>
          ) : (
            <div className="space-y-0.5">
              {states.map(state => (
                <StateItem
                  key={state.code}
                  state={state}
                  compact={compact}
                  readonly={readonly}
                  isEditing={editingCode === state.code}
                  onEdit={onEdit ? () => onEdit(state.code) : undefined}
                  onDelete={onDelete ? () => onDelete(state.code) : undefined}
                  onSave={onSaveEdit ? (updates) => onSaveEdit(state.code, updates) : undefined}
                  onCancel={onCancelEdit}
                />
              ))}
            </div>
          )}
        </div>
      )}
    </div>
  )
}

interface StateItemProps {
  state: GraphState
  compact?: boolean
  readonly?: boolean
  isEditing?: boolean
  onEdit?: () => void
  onDelete?: () => void
  onSave?: (updates: Partial<GraphState>) => void
  onCancel?: () => void
}

function StateItem({
  state,
  compact = false,
  readonly = false,
  isEditing = false,
  onEdit,
  onDelete,
  onSave,
  onCancel,
}: StateItemProps) {
  const [editForm, setEditForm] = useState({
    name: state.name,
    description: state.description || '',
    semantic_tags: state.semantic_tags?.join(', ') || '',
  })

  if (isEditing && onSave && onCancel) {
    return (
      <div className="p-2 bg-[#1a1a2e] rounded border border-blue-500/30 space-y-2">
        <input
          type="text"
          value={editForm.name}
          onChange={(e) => setEditForm(prev => ({ ...prev, name: e.target.value }))}
          className="w-full px-2 py-1 bg-[#0f0f1a] border border-[#2a2a4a] rounded text-xs text-white focus:outline-none focus:border-blue-500"
          placeholder="State name"
        />
        <input
          type="text"
          value={editForm.description}
          onChange={(e) => setEditForm(prev => ({ ...prev, description: e.target.value }))}
          className="w-full px-2 py-1 bg-[#0f0f1a] border border-[#2a2a4a] rounded text-xs text-gray-400 focus:outline-none focus:border-blue-500"
          placeholder="Description"
        />
        <input
          type="text"
          value={editForm.semantic_tags}
          onChange={(e) => setEditForm(prev => ({ ...prev, semantic_tags: e.target.value }))}
          className="w-full px-2 py-1 bg-[#0f0f1a] border border-[#2a2a4a] rounded text-xs text-purple-400 focus:outline-none focus:border-blue-500"
          placeholder="Tags (comma separated)"
        />
        <div className="flex justify-end gap-1">
          <button
            onClick={onCancel}
            className="p-1 text-gray-500 hover:text-gray-400 rounded"
          >
            <X className="w-3 h-3" />
          </button>
          <button
            onClick={() => onSave({
              name: editForm.name,
              description: editForm.description || undefined,
              semantic_tags: editForm.semantic_tags
                ? editForm.semantic_tags.split(',').map(t => t.trim()).filter(Boolean)
                : undefined,
            })}
            className="p-1 text-green-500 hover:text-green-400 rounded"
          >
            <Check className="w-3 h-3" />
          </button>
        </div>
      </div>
    )
  }

  return (
    <div className={`flex items-center gap-2 ${compact ? 'px-1.5 py-1' : 'px-2 py-1.5'} rounded hover:bg-[#1a1a2e] group transition-colors`}>
      {/* Color indicator */}
      <div
        className="w-2.5 h-2.5 rounded-full flex-shrink-0"
        style={{ backgroundColor: state.color || '#6B7280' }}
      />

      {/* State info */}
      <div className="flex-1 min-w-0">
        <div className="flex items-center gap-1.5">
          <span className={`${compact ? 'text-[10px]' : 'text-xs'} text-gray-300 truncate`}>
            {state.name}
          </span>
          {state.phase && (
            <span className="text-[8px] px-1 py-0.5 rounded bg-gray-700/50 text-gray-500">
              {state.phase}
            </span>
          )}
        </div>
        <div className="text-[9px] text-gray-600 truncate">{state.code}</div>
        {state.semantic_tags && state.semantic_tags.length > 0 && (
          <div className="flex flex-wrap gap-0.5 mt-0.5">
            {state.semantic_tags.slice(0, 3).map(tag => (
              <span key={tag} className="text-[8px] px-1 py-0.5 rounded bg-purple-500/10 text-purple-400">
                {tag}
              </span>
            ))}
            {state.semantic_tags.length > 3 && (
              <span className="text-[8px] text-gray-600">+{state.semantic_tags.length - 3}</span>
            )}
          </div>
        )}
      </div>

      {/* Actions */}
      {!readonly && (
        <div className="flex items-center gap-0.5 opacity-0 group-hover:opacity-100 transition-opacity">
          {onEdit && (
            <button
              onClick={onEdit}
              className="p-1 text-gray-500 hover:text-blue-400 rounded"
            >
              <Edit2 className="w-3 h-3" />
            </button>
          )}
          {onDelete && (
            <button
              onClick={onDelete}
              className="p-1 text-gray-500 hover:text-red-400 rounded"
            >
              <Trash2 className="w-3 h-3" />
            </button>
          )}
        </div>
      )}
    </div>
  )
}

interface AddStateFormProps {
  onAdd: (state: GraphState) => void
  onCancel: () => void
  existingCodes: string[]
}

function AddStateForm({ onAdd, onCancel, existingCodes }: AddStateFormProps) {
  const [form, setForm] = useState({
    code: '',
    name: '',
    description: '',
    color: '#6B7280',
    semantic_tags: '',
  })
  const [error, setError] = useState<string | null>(null)

  const handleSubmit = () => {
    if (!form.code.trim()) {
      setError('Code is required')
      return
    }
    if (!form.name.trim()) {
      setError('Name is required')
      return
    }
    if (existingCodes.includes(form.code.trim())) {
      setError('State code already exists')
      return
    }

    onAdd({
      code: form.code.trim(),
      name: form.name.trim(),
      type: 'custom',
      color: form.color,
      description: form.description.trim() || undefined,
      semantic_tags: form.semantic_tags
        ? form.semantic_tags.split(',').map(t => t.trim()).filter(Boolean)
        : undefined,
    })
  }

  return (
    <div className="p-2 bg-[#1a1a2e] rounded-lg border border-[#2a2a4a] space-y-2">
      <div className="text-xs font-medium text-gray-400 mb-2">New Custom State</div>

      <div className="flex gap-2">
        <input
          type="text"
          value={form.code}
          onChange={(e) => {
            setForm(prev => ({ ...prev, code: e.target.value }))
            setError(null)
          }}
          className="flex-1 px-2 py-1 bg-[#0f0f1a] border border-[#2a2a4a] rounded text-xs text-white focus:outline-none focus:border-blue-500"
          placeholder="State code (e.g., waiting)"
        />
        <input
          type="color"
          value={form.color}
          onChange={(e) => setForm(prev => ({ ...prev, color: e.target.value }))}
          className="w-8 h-8 rounded border border-[#2a2a4a] bg-transparent cursor-pointer"
        />
      </div>

      <input
        type="text"
        value={form.name}
        onChange={(e) => {
          setForm(prev => ({ ...prev, name: e.target.value }))
          setError(null)
        }}
        className="w-full px-2 py-1 bg-[#0f0f1a] border border-[#2a2a4a] rounded text-xs text-white focus:outline-none focus:border-blue-500"
        placeholder="Display name"
      />

      <input
        type="text"
        value={form.description}
        onChange={(e) => setForm(prev => ({ ...prev, description: e.target.value }))}
        className="w-full px-2 py-1 bg-[#0f0f1a] border border-[#2a2a4a] rounded text-xs text-gray-400 focus:outline-none focus:border-blue-500"
        placeholder="Description (optional)"
      />

      <input
        type="text"
        value={form.semantic_tags}
        onChange={(e) => setForm(prev => ({ ...prev, semantic_tags: e.target.value }))}
        className="w-full px-2 py-1 bg-[#0f0f1a] border border-[#2a2a4a] rounded text-xs text-purple-400 focus:outline-none focus:border-blue-500"
        placeholder="Semantic tags (comma separated)"
      />

      {error && (
        <div className="text-[10px] text-red-400">{error}</div>
      )}

      <div className="flex justify-end gap-2 pt-1">
        <button
          onClick={onCancel}
          className="px-2 py-1 text-xs text-gray-500 hover:text-gray-400"
        >
          Cancel
        </button>
        <button
          onClick={handleSubmit}
          className="px-2 py-1 text-xs text-blue-400 bg-blue-500/20 rounded hover:bg-blue-500/30"
        >
          Add State
        </button>
      </div>
    </div>
  )
}

// Helper to get all available states (system + graph + custom)
export function getAllStates(
  graphStates: GraphState[],
  autoGenerateStates: boolean,
  stepIds: string[]
): GraphState[] {
  const states = [...SystemStates]

  // Add auto-generated states if enabled
  if (autoGenerateStates) {
    const phases: StatePhase[] = ['executing', 'success', 'failed']
    stepIds.forEach(stepId => {
      phases.forEach(phase => {
        const code = `${stepId}:${phase}`
        if (!graphStates.some(s => s.code === code)) {
          states.push({
            code,
            name: `${stepId} (${phase})`,
            type: 'graph',
            step_id: stepId,
            phase,
            color: PHASE_COLORS[phase],
            semantic_tags: [phase, stepId],
          })
        }
      })
    })
  }

  // Add explicitly defined states
  states.push(...graphStates)

  return states
}

// Helper to get all unique semantic tags
export function getAllSemanticTags(states: GraphState[]): string[] {
  const tags = new Set<string>()
  states.forEach(state => {
    state.semantic_tags?.forEach(tag => tags.add(tag))
  })
  return Array.from(tags).sort()
}
